### ISSUE TITLE
ActiveMerchant::ConnectionError (The connection to the remote server timed out):

### ISSUE THREAD

**Issue by MohdAnas** [activemerchant/active_merchant#1058]
I am using active merchant for credit card payment. Everything was working fine but suddenly it stops working and giving an error ActiveMerchant::ConnectionError (The connection to the remote server timed out). I did not even touch the code. Can anyone tell me why i am getting this error?

Thanks in Advance

**Comment by ctpelnar1988** [comment]
I encountered the same issue. The problem was that I was passing "United States" as the country_code value instead of "US".
