### ISSUE TITLE
Paypal REST API?

### ISSUE THREAD

**Issue by fotanus** [activemerchant/active_merchant#1274]
Hello,

It seems that paypal is moving to a [REST API](https://developer.paypal.com/docs/api). Does active merchant support this API, or plan to support it? 

Note that there is already a [paypal gem for that](https://github.com/paypal/rest-api-sdk-ruby)

Thanks!

**Comment by EppO** [comment]
According to [Paypal](https://github.com/paypal/merchant-sdk-ruby#merchant): 
"This Classic SDK is not actively supported and will be deprecated in the future. For full support on new integrations, please use the Ruby Rest SDK"
Can you reconsider to reopen this issue and #790 ?

**Comment by girasquid** [comment]
@EppO You may want to check with PayPal, but I believe that line is referring to that particular library (not the API that it uses).

**Comment by ntalbott** [comment]
@EppO yup, ActiveMerchant doesn't use the PayPal library, so that's not an issue for us. Unless you can find them publicly stating that they're deprecating the SOAP API, we have no plans to move.

**Comment by EppO** [comment]
fair enough. My perception is that they stop supporting APIs that consume there SOAP API in order to motivate people to move on the REST API and then deprecate their old/classic API. I'm maybe wrong.

**Comment by eneeyac** [comment]
I may be wrong but it seems Paypal classic api does not have any equivalent for vaults https://developer.paypal.com/webapps/developer/docs/api/#vault

**Comment by ntalbott** [comment]
@eneeyac if someone wants to add `store` support and it requires the REST API, we would consider that in context. There happening to be extra functionality that AM doesn't need at present isn't a factor here, though.
