### ISSUE TITLE
Merging in pull requests

### ISSUE THREAD

**Issue by duff** [activemerchant/active_merchant#1441]
Hi @Shopify/active-merchant,

I've only been a maintainer on the project for a short time and I've noticed that, like on all projects, there are different styles and approaches folks are taking.  When merging in pull requests, I've been following the recipe @ntalbott laid out in this blog post:

http://bit.ly/1iF8uJn

and I've been pretty happy with the results.  I've even started using parts of it in our other Spreedly internal projects.

I'm curious what y'all might think of the approach and whether it has merit.

**Comment by duff** [comment]
I'm still seeing some icky "Merge Pull Request" commits come through from @bizla, @andrewpaliga, @jnormore, and @j-mutter in the history which makes me :cry: a little but I'm getting over it.

Perhaps there's no way to resist the allure of the `Merge Pull Request` button.

**Comment by j-mutter** [comment]
Heh, yeah - force of habit. I've been trying to avoid it recently, but this is the only repo we do manual merges on, and I forget 😞
