### ISSUE TITLE
Active merchant says Invalid card for a valid card

### ISSUE THREAD

**Issue by pamio** [activemerchant/active_merchant#1452]
Hi, 
I have been facing this issue for sometime now and I have raised an SO question also, the link to which is http://stackoverflow.com/questions/26713398/activemerchant-says-invalid-credit-card-for-a-valid-card. 
First I thought that this is a problem with JCB cards but this also happens with master cards. So I'm not sure if there's a configuration problem or something else. 

here is what I did 

2.1.1 :056 > cc = CreditCard.new(:first_name => 'Steve',:last_name => 'Smith', :month => '9',:year => '2015',:number => '3088023605344101', :verification_value => '123')
=> #<ActiveMerchant::Billing::CreditCard:0x0000010a0d91d8 @first_name="Steve", @last_name="Smith", @month="9", @year="2015", @number="3088023605344101", @verification_value="123"> 
2.1.1 :057 > cc.valid?
=> false 
2.1.1 :058 > cc.errors
=> {"brand"=>["is required"], "number"=>[]}     

Then i fed brand

2.1.1 :059 > cc = CreditCard.new(:first_name => 'Steve',:last_name => 'Smith', :month => '9',:year => '2015',:number => '3088023605344101', :verification_value => '123', :brand => 'jcb')
=> #<ActiveMerchant::Billing::CreditCard:0x00000109d886c8 @first_name="Steve", @last_name="Smith", @month="9", @year="2015", @number="3088023605344101", @verification_value="123", @brand="jcb"> 
2.1.1 :060 > cc.valid?
=> false 
2.1.1 :061 > cc.errors
=> {"number"=>[], "brand"=>["does not match the card number"]} 

why should this happen ? I have already verified card numbers.

**Comment by fuckofbitch** [comment]
I hope this work
