### ISSUE TITLE
PayU Latam integration

### ISSUE THREAD

**Issue by bbozo** [activemerchant/active_merchant#1482]
Dear all,

I would like to add PayU Latam support to Shopify, if I do this will you be willing to accept it to your official list of payment providers?

http://www.payulatam.com/

PayU Latam is one of those services which support credit cards and cash where client gets redirected to a separate page and as a result the shop receives a POST callback for transaction status update + the redirected client. In case of cash payments a POST callback will land to confirm the transaction once the client transfers funds via his bank.

If you aren't interested in supporting this gateway, do you have a guideline / doc for custom integrations?

Kind regards :)

**Comment by yoseldvp** [comment]
Alguna actualización sobre este desarrollo?, todavía no veo esta integración en shopify

**Comment by batusai513** [comment]
Any news for payu colombia?

**Comment by andrewpaliga** [comment]
@batusai513 we are still waiting for integration work from PayU Latam

**Comment by fpinzn** [comment]
Any updates?

**Comment by j-mutter** [comment]
Nothing in the last 21 hours, no.

**Comment by fpinzn** [comment]
Sorry, I misread @andrewpaliga post.

**Comment by mayaibuki** [comment]
I'm still waiting for PayU Latam. I'm not a fan of it but is the best (and practically the only) option for shopify in Colombia
