### ISSUE TITLE
Gateway's 'unstore' method is not "tell-don't-ask"

### ISSUE THREAD

**Issue by kikito** [activemerchant/active_merchant#1490]
The current implementation of unstore in gateways allows for some gateways to not define it, while others do. As a result, when you want to use it, you must check (or worse, manually maintain your own list of payment gateways supporting unstoring)

``` ruby
def unstore_credit_card_info(reference)
  response = current_gateway.respond_to?(:unstore) ? current_gateway.unstore(reference) : "not permitted"
  do_something_with_response(response)
end
```

You have to do the check even if you don't care about the response:

``` ruby
def unstore_credit_card_info_without_response(reference)
  current_gateway.unstore(reference) if current_gateway.respond_to?(:unstore)
end
```

I propose a default implementation of unstore in [Gateway](https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/billing/gateway.rb) which does nothing and returns `nil`.

That way, the code above could be rewritten like this:

``` ruby
def unstore_credit_card_info(reference)
  response = current_gateway.unstore(reference) || "not permitted"
  do_something_with_response(response)
end
```

And if you don't care about the response, you can just call the method:

``` ruby
def unstore_credit_card_info_without_response(reference)
  current_gateway.unstore(reference)
end
```

If detecting the support for `unstore` by detecting a falsy response is not possible/dessirable, another would be implementing a `can_unstore?` method returning true in if `unstore` does something, and false if it does nothing. Then the "case where response is used" is not significantly better:

``` ruby
def unstore_credit_card_info(reference)
  response = current_gateway.can_unstore? current_gateway.unstore(reference) : "not permitted"
  do_something_with_response(response)
end
```

But at least the other case is simpler:

``` ruby
def unstore_credit_card_info_without_response(reference)
  current_gateway.unstore(reference)
end
```

**Comment by akostadinov** [comment]
If op, you and other users create an abstraction over AM, then maybe that abstraction is worth to be part of AM. Just saying. I just saw we also have such an abstraction over the unstoring specifically and I was wondering whether we have been doing something wrong.
