### ISSUE TITLE
RFC: ActiveMerchant 2.x

### ISSUE THREAD

**Issue by ntalbott** [activemerchant/active_merchant#1584]
@Shopify/active-merchant I'd like to propose that we cut an ActiveMerchant 2.0 in the near future. The goal would be to remove a lot of crufty backwards compatibility and deprecations. Off the top of my head:
- drop support for recurring
- drop support for `Money`
- review all public gateway methods and bring them inline with what AM supports, either via shifting args around and/or cutting them
- drop the unnecessary `billing` intermediate directory
- no more autoload
- explicit requires only, no requiring the world
- etc.

I'd be happy to spearhead this, and would propose:
- [ ] create a 1.x branch
- [ ] master becomes 2.x
- [ ] all changes go into master first, and get backported to 1.x if we need it or it's requested
- [ ] we make the changes, let it bake for a few weeks, cut an RC or two, roll RC's to our respective apps, and the cut a 2.0 once all looks good.
- [ ] once 2.0 final is cut in gem form, we only do new 1.x gems for security fixes

Thoughts?

**Comment by girasquid** [comment]
This sounds pretty awesome.

**Comment by wvanbergen** [comment]
> drop support for Money

:+1: But we should use a well documented, standard way of passing around monetary values (including currency)

> no more autoload

You mean you have to explicitly require the gateway you're using?

**Comment by wvanbergen** [comment]
I'll add: as an abstraction library we should define the abstraction we define much more strictly. Mostly in terms of documentation, but also tooling around it. 

E.g. `def purchase(amount, payment, options = {})`. What is `amount`? What is `payment`? What keys in `options` have special meaning, and what keys can you use for gateway specific things? What does it return? How do we make sure new gateways conform to this contract?

**Comment by girasquid** [comment]
> define the abstraction we define much more strictly

:+1: for this.

**Comment by wvanbergen** [comment]
Maybe: remove `builder` dependency for generating XML? (This will require rewriting a bunch of gateways using Nokogiri instead)

**Comment by ntalbott** [comment]
@wvanbergen I'm totally down with getting more strict; my only hesitation is tying that to v2. I'd like to focus v2 mostly on removing cruft, and moving towards more consistent abstraction without actual enforcement thereof yet. Mostly I just don't want to try to do so much that v2 never gets cut.

I'm thinking we do a lot of cleanup in v2, and once it's cut we can start adding tools that we can run across new changes to validate our desired API abstraction. Then we can move that validation into the codebase and get actively strict about it come v3.

**Comment by ntalbott** [comment]
I actually think removing `Builder` doesn't have to be tied to v2, since it should have no external API effect. So big :+1:, but no need to either wait for v2 or hold up v2.

**Comment by ntalbott** [comment]
@wvanbergen in terms of requires, yes, I want to make users explicitly require gateways they use. I also want to ditch the huge "require everything" file that is https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant.rb and instead have each file require only what it needs.

**Comment by j-mutter** [comment]
Yeah I would be wary of trying to do too much for v2

**Comment by ntalbott** [comment]
Full speed ahead sounds like! Going to make it so.

**Comment by bizla** [comment]
I'll always :+1: cruft removal efforts.

**Comment by alovak** [comment]
Guys, what do you think about extracting gateways into separate gems? pros/cons of such solution?

**Comment by ntalbott** [comment]
@alovak for 2.0 I'm :-1:, that's outside of scope from my opinion.

That said, I've thought a *lot* about this, and my thinking is that ActiveMerchant should always have a lot of built in gateways, that the AM maintainers explicitly support. But, I want to make it easy for odd gateways, or gateways that for some reason can't/won't follow our coding conventions, new gatewyas that the maintainers aren't sure will make it, etc., to offer sidecar gems to plug their gateway into AM.

For instance, I'd like to kick Braintree out of ActiveMerchant "core" due to their annoying gem-only policy. I'd also consider kicking out all gateways that won't provide public test credentials for the maintainers. And I'd like to make the majority of new gateways start out as sidecar gems before getting pulled into AM core.

So, that's my $0.02.

**Comment by bizla** [comment]
I'm with @ntalbott on all of this. I'd rather keep the ecosystem stable inside one gem and promote best practices for new integrations as much as possible. I'm fully on board with a quality policy too: I'd ideally like to see AM2 provide a "remote-testable" guarantee and have gateways provide/maintain API credentials for remote testing. Overly stale credentials could be construed as a disinterest in staying integrated in AM (and thus Spreedly and Shopify.) 

I also think it would make sense for there to exist a "core" API and then something like an **active_merchant_extensions** (working title :wink:) that takes care of integrations that don't/can't cleanly follow the API -- but are necessary to integrate -- like a Braintree. 

I'd also like for us to consider [removing any consideration for Ruby 1.9 compatibility](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/).

**Comment by j-mutter** [comment]
@bizla done :)
https://github.com/Shopify/active_merchant/pull/1583

**Comment by bizla** [comment]
:heart_eyes: @j-mutter you continue to be a wind beneath my wings

**Comment by ntalbott** [comment]
@bizla all :+1:, except I think this is more AMv3; v2 is...

:musical_note: All about that cruft, bout that cruft, no features, ... :musical_note:.

**Comment by bpollack** [comment]
@ntalbot Should I close this (and other v2.0) issues at this point? There doesn't appear to have been movement for three years.

**Comment by bpollack** [comment]
@ntalbott Should I close this (and other v2.0) issues at this point? There doesn't appear to have been movement for three years.

**Comment by ntalbott** [comment]
@bpollack yah. Such big dreams...
