### ISSUE TITLE
JetPay REVERSEAUTH not implemented - use .void?

### ISSUE THREAD

**Issue by brokenbeatnik** [activemerchant/active_merchant#1606]
Looking at the JetPay integration, it appears that REVERSEAUTH is not implemented. Moreover, the gateway specification does not have a method for reversing an auth, only .void and .refund. .void in this case implements the VOID call in JetPay, which reverses a captured but unsettled transaction. 

The approach I would like to take is to fork, implement a REVERSEAUTH call triggered by a flag passed into .void's options hash (e.g. {auth: true} to indicate that the voided transaction is only an auth). I'll submit that back as a pull request when I can. First though, I wanted to confirm that I'm accurately identifying an issue with the ActiveMerchant JetPay integration.

I welcome any guidance you can provide.

https://www.jetpay.com/resources/library/pdf/xml/JetPay_XML_Specification-20120216.pdf 
(Section 3.6.1 identifies the difference between VOID and REVERSEAUTH)

**Comment by aprofeit** [comment]
Based on the comments in https://github.com/activemerchant/active_merchant/pull/1607 I'm going to close this since it sounds like we're waiting for jetpay to allow voiding an auth instead of adding a new method to AM. Feel free to reopen if I'm mistaken.
