### ISSUE TITLE
Integration with asynchronous api

### ISSUE THREAD

**Issue by dinesh** [activemerchant/active_merchant#1637]
We want to integrate our new api (Quickpay v10) with AM but the problem is, it's asynchronous and a client has to poll for the success of any response ( in terms of authorize, capture).   

Is there any standard pattern for supporting such API in active_merchant currently ? If not, I will also appreciate any workaround.

**Comment by davidsantoso** [comment]
Hi @dinesh - this is a bit stale but this isn't something we currently or are looking to support with Active Merchant.

**Comment by dinesh** [comment]
@davidsantoso got it. We finally supported synchronous api. Can be closed now.
