### ISSUE TITLE
Activemerchant SSL_connect returned=1 errno=0 state=SSLv3

### ISSUE THREAD

**Issue by holy-cow** [activemerchant/active_merchant#1643]
I'm getting this error when creating new Paypal notification with active merchant

```ruby
class PaymentNotificationsController < ApplicationController
  include ActiveMerchant::Billing::Integrations

  protect_from_forgery except: :create

  def create
    notify = Paypal::Notification.new(request.raw_post)
```

Error:

A OpenSSL::SSL::SSLError occurred in payment_notifications#create: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed /home/user/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/net/http.rb:918:in `connect'

Activemerchant version: 1.47.0
Ruby version: ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-linux]
Rails version: 3.2.16
Ubuntu version: Ubuntu 14.04.2 LTS
Openssl version: OpenSSL 1.0.1f 6 Jan 2014

**Comment by ntalbott** [comment]
@holy-cow for some reason your AM is choosing to use an SSLv3 connection, which PayPal no longer supports. I'd start by using a more up to date Ruby - at least the most recent patch version of 2.0 - and see if that helps.

**Comment by hadronzoo** [comment]
See also: http://stackoverflow.com/questions/4528101/ssl-connect-returned-1-errno-0-state-sslv3-read-server-certificate-b-certificat

**Comment by steakchaser** [comment]
Also ran into this issue today in production.  From what I can tell, Authorize.net did not upgrade the https://apitest.authorize.net/xml/v1/request.api endpoint (and, has still not).  Huge surprise for us.

Using Ruby 1.9.3-p448, OpenSSL 1.0.1f 6 Jan 2014 on Heroku.

What is the official way to direct the gateway to use TLSv1?  

Is it like what's outline here in [this post](https://www.new-bamboo.co.uk/blog/2013/06/13/custom-activemerchant-connections/)?  I also see that some gateways (like`OgoneGateway`) have added `self.ssl_version = :TLSv1` themselves.  Help.

**Comment by hackbac** [comment]
@steakchaser: patching `ActiveMerchant::Connection.configure_ssl` to comment out the hardcoded reference to the CA certificate worked for me. Without a valid ca_file or ca_path or cert_store, OpenSSL will default to its own certificate store.
```
module ActiveMerchant
  class Connection
    def configure_ssl(http)
      return unless endpoint.scheme == "https"

      http.use_ssl = true

      if verify_peer
        http.verify_mode = OpenSSL::SSL::VERIFY_PEER
        # Fix SSLv3 failure
        # http.ca_file     = File.dirname(__FILE__) + '/../../certs/cacert.pem'
      else
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      end
    end
  end
end
```
