### ISSUE TITLE
CreditCard require_verification_value instance method removed

### ISSUE THREAD

**Issue by danlewis** [activemerchant/active_merchant#1646]
Was a bit surprised to find in version 1.48.0 in ActiveMerchant::Billing::CreditCard the method require_verification_value was removed as an instance method without mention in the change logs.

Previously calling this per payment

```ruby
cc =ActiveMerchant::Billing::CreditCard.new(...)
cc.require_verification_value = !cvn_bypass?
```
seemed much nicer than this:
```ruby
ActiveMerchant::Billing::CreditCard.require_verification_value = !cvn_bypass?
cc = ActiveMerchant::Billing::CreditCard.new(...)
```

require_verification_value should be true by default but be able to be set per instance as previously.

Thanks

**Comment by ntalbott** [comment]
@danlewis I don't remember this ever having been an instance variable - can you show me the commit where this changed?

I do agree that it's a bit odd to have it as a class variable, but I don't believe there's actually been a change on that point any time recently.

**Comment by danlewis** [comment]
I'm not sure exactly which commit it happened but you can see when I switch the following works
1.47.0: 
```ruby
2.2.1 :006 > ActiveMerchant::Billing::CreditCard.require_verification_value
 => true 
2.2.1 :007 > ActiveMerchant::Billing::CreditCard.new.require_verification_value
 => true
```

1.48.0:
```ruby
2.2.1 :007 > ActiveMerchant::Billing::CreditCard.require_verification_value
 => true 
2.2.1 :008 > ActiveMerchant::Billing::CreditCard.new.require_verification_value
NoMethodError: undefined method `require_verification_value' for #<ActiveMerchant::Billing::CreditCard:0x007fbee3ec3368>

**Comment by ntalbott** [comment]
I think this was an unintentional affect of the change away from using `cattr_accessor` in https://github.com/Shopify/active_merchant/commit/c97e7f3a0e82e6eeff356a35f0b11c388e138163#diff-5f60353ee3917b9a473e169bde83d99d. @rwdaigle any thoughts on bringing back the instance level access?

**Comment by ericgross** [comment]
+1 Hitting this too after upgrading.

**Comment by rwdaigle** [comment]
Wow, sorry I didn't see this until now. Poor GH notification management on my part.

This changed was [introduced](https://github.com/Shopify/active_merchant/pull/1596#discussion_r25869025) to allow `CreditCard` sub-classes to maintain their own `require_verification_value` default value without affecting `CreditCard`. Any modification of instance access was unintentional.

Instance access is fine by me, as long as it retains the ability to set subclass values that are independent from `CreditCard`.

**Comment by amnwebmaster** [comment]
Any chance the instance method require_verification_value will be added back in?

**Comment by aprofeit** [comment]
Looks like this was added back in https://github.com/activemerchant/active_merchant/commit/43e8adf2.
```
irb(main):035:0> card = ActiveMerchant::Billing::CreditCard.new(first_name: 'Alex', last_name: 'Profeit', number: '4242424242424242', year: '2016', month: '1')
=> #<ActiveMerchant::Billing::CreditCard:0x007ff8b0a6f5f8 @first_name="Alex", @last_name="Profeit", @month=1, @year=2016, @number="4242424242424242">
irb(main):036:0> card.valid?
/home/vagrant/src/rails/active_merchant/lib/active_merchant/billing/compatibility.rb:6:in `valid?': Implicit inclusion of Rails-specific functionality is deprecated. Explicitly require "active_merchant/billing/rails" if you need it.
=> false
irb(main):037:0> card.errors
/home/vagrant/src/rails/active_merchant/lib/active_merchant/billing/compatibility.rb:11:in `errors': Implicit inclusion of Rails-specific functionality is deprecated. Explicitly require "active_merchant/billing/rails" if you need it.
=> {"verification_value"=>["is required"]}
irb(main):038:0> card.require_verification_value = false
=> false
irb(main):039:0> card.valid?
/home/vagrant/src/rails/active_merchant/lib/active_merchant/billing/compatibility.rb:6:in `valid?': Implicit inclusion of Rails-specific functionality is deprecated. Explicitly require "active_merchant/billing/rails" if you need it.
=> true
irb(main):040:0>
```
