### ISSUE TITLE
OFFSITE_PAYMENT_EXTRACTION_MESSAGE removed but still referenced

### ISSUE THREAD

**Issue by alex-ut** [activemerchant/active_merchant#1661]
The constant `OFFSITE_PAYMENT_EXTRACTION_MESSAGE` was removed by d730e442a7aa0bb7f88b705c2a1a811c703e479f , but it is still referenced [here](https://github.com/Shopify/active_merchant/blob/456cf85cab51d161960ebfde1944f0f76f77e54d/lib/active_merchant/billing/base.rb#L13-L18).

Calling `ActiveMerchant::Billing::Base.integration_mode = :test` causes:

```[...] lib/active_merchant/billing/base.rb:13:in `integration_mode=': uninitialized constant ActiveMerchant
::Billing::Base::OFFSITE_PAYMENT_EXTRACTION_MESSAGE (NameError)```

**Comment by lafeber** [comment]
:+1:
