### ISSUE TITLE
QUESTION: Encrypted track data for card present transactions?

### ISSUE THREAD

**Issue by theinventor** [activemerchant/active_merchant#1751]
Hey all - 

We are considering adding support for encrypted swiping to the mercury gateway. 

I suppose we need to use like track2 data and also be able to pass some other kind of token?

1. Are there are gateways in here that support encrypted readers for card present stuff?
2. If we do it, is there a chance (good chance?) it can get merged upstream if we build it well?
3. If no on 2, do others maintain a monkey patch in their app, or a fork with their gateway, or?

I'm not totally new to this, we've been using a few gateways in AM for a few years now - and would love to help beef it up in this area if maintainers are open to it.

Happy to take this offline too - let me know

**Comment by theinventor** [comment]
@ntalbott looks like you've done some work on the mercury stuff - if you have any additional insight into how that gateway works, and maybe encryption in general, you could save me a lot of work :smile:

**Comment by ntalbott** [comment]
@theinventor it's been quite a while, and all that info is unloaded from my brain, sorry :(. I wonder if this might be related to the work Shopify has been doing around EMV in the Stripe gateway?

**Comment by theinventor** [comment]
@ntalbott unrelated - no prob.

Another way to put this; 

A lot of these gateways accept "Track1 Data" as a string, that string usually has the full card number, expiration, etc - and they are calling that a "card present" transaction.

You can get a USB/other swiper for a computer that comes with encryption loaded for a specific gateway. Then that Track1 data will be masked, there will be additional encrypted data and a token included in the string of junk you get from the swiper. You can send that to your gateway and "only they" can decrypt it.

It takes you out of PCI scope, while basically anyone else using this gem is IN scope.

**Comment by ntalbott** [comment]
@theinventor right, understood. What changes do you imagine will be necessary for Mercury, though?Sounds like you just need to pass through encrypted data vs passing through decrypted data?

**Comment by theinventor** [comment]
I think we'll want to add a gateway for mercury's REST endpoint, the existing one is their SOAP - can we do that and call it "mercury-rest" or "mercury-encrypted" ?

The purpose will be to accepted encrypted track data, and send that plus the encryption key to their API.

Maybe we make some new subclass of the "CreditCard" class called "EncryptedCard" or something, so we can add the encryption key there?

**Comment by girasquid** [comment]
> I think we'll want to add a gateway for mercury's REST endpoint, the existing one is their SOAP - can we do that and call it "mercury-rest" or "mercury-encrypted" ?

If the REST endpoint supports everything that the current Mercury implementation needs, could we just update it to use the SOAP endpoint instead? Having two implementations for the same gateway isn't great if it's not required.

> Maybe we make some new subclass of the "CreditCard" class called "EncryptedCard" or something, so we can add the encryption key there?

:+1: for this - here's an example for network tokenization: https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/network_tokenization_credit_card.rb

**Comment by theinventor** [comment]
@girasquid this says "EMV" - I'm not sure this is applicable to an "encrypted magnetic stripe reader", do you know?

Also - are you saying you prefer using SOAP over rest??
(that's crazy)

**Comment by girasquid** [comment]
Sorry - it looks like I got mixed up writing that.

1. If the REST endpoint supports everything that the current (SOAP) implementation needs, could we update the current (SOAP) implementation to use the REST endpoints, and kill two birds with one stone? You'd get the new functionality AND less SOAP.

2. Making a new subclass for encrypted cards makes sense; I added a link to the network tokenization card as an example of us doing it for another payment flow in the past.

**Comment by ntalbott** [comment]
@theinventor does the SOAP API support encrypted card data?

**Comment by theinventor** [comment]
@ntalbott I only have the API doc for rest, we'll only work with the REST one..

**Comment by ntalbott** [comment]
@theinventor while REST is new and shiny, we have a completely working implementation against the SOAP API already, and Mercury is complicated enough I'm not keen to muck with a working implementation. Thus I'd **much** prefer a PR that just adds what you want using the existing SOAP code, vs. completely replacing the gateway.

@girasquid curious your thoughts - think a full rewrite is worth it?

**Comment by girasquid** [comment]
If the SOAP API supports it, my vote would be to stay with that and have a small, focused PR. If it doesn't, having support for it in AM would mean rewriting - I'd prefer that over having two implementations for the same gateway.

**Comment by theinventor** [comment]
Ok - that makes sense, I'll get a doc on their SOAP API and see if it supports it. 

If so, we'll see what we can do to add it that route.

Otherwise - understanding we might have to just be ok with this not getting upstream, I'll do what we can - thanks!

Want to close this until I hear back?

**Comment by girasquid** [comment]
Done! Let us know what you learn.

**Comment by ntalbott** [comment]
@theinventor if encrypted track data isn't supported via the SOAP API, I'll be much more inclined to consider a rewrite against the REST API.

Look forward to hearing what you find out!

**Comment by theinventor** [comment]
They just told me the REST API is actually just using the SOAP API — haha.. so.. yeah, it supports everything.

We’ll see if our dev is up for doing it next..

**Comment by theinventor** [comment]
@ntalbott @girasquid I forgot to try to get this merged upstream, but we've been using this a while in production now and thought I would see what you guys think.

Pull Request:
https://github.com/activemerchant/active_merchant/pull/1965

Basically, when you swipe a credit card with an encrypted reader it masks a couple digits in the middle of the card number (they become "0000") and it adds an area to the end of the string with encrypted data. You have to pull some bits out and send them to mercury, they are able to decrypt.

Now you've run a transaction without ever touching the real card data un-encrypted.

My understanding is we needed a new concept to store this encrypted blob in active merchant, but I think it was implemented in a nice way.

Happy to answer more questions (and we'll fix that test failure too I guess)
