### ISSUE TITLE
Test output looks crazy

### ISSUE THREAD

**Issue by aprofeit** [activemerchant/active_merchant#1754]
The colored output seems to not print some letters and leaves gaps in strange places.

![screen shot 2015-06-24 at 10 01 21 am](https://cloud.githubusercontent.com/assets/1313339/8331789/269d5d62-1a58-11e5-8f65-a72b38318f76.png)

**Comment by ntalbott** [comment]
@aprofeit that's a diffing algorithm; above you see the full expected/actual, and underneath is a diff of them. Sometimes the diff is useless, but other times it's super helpful.

**Comment by aprofeit** [comment]
Ooohhhhh, that makes sense. Thanks!
