### ISSUE TITLE
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by puneetimpinge** [activemerchant/active_merchant#1760]
I am getting error on apache server: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed, on Authorize.net payment.

I have an application in which AM plugin is used in vendor folder.
AM version: 1.4.2
Ruby: ruby 1.8.7 (2013-06-27 patchlevel 374)
Rails: 2.3.18

AM works properly on my local machine but not on server. I tried to do payment using rails console manually and then what I got:

OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
	from /usr/local/rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/net/http.rb:586:in `connect'
	from /usr/local/rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/net/http.rb:586:in `connect'
	from /usr/local/rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/net/http.rb:553:in `do_start'
	from /usr/local/rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/net/http.rb:542:in `start'
	from /usr/local/rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/net/http.rb:1035:in `request'
	from /usr/local/rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/net/http.rb:845:in `post'
	from /var/www/html/dormbuys/vendor/plugins/active_merchant/lib/active_merchant/lib/connection.rb:67:in `request'
	from /usr/local/rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/benchmark.rb:308:in `realtime'
	from /var/www/html/dormbuys/vendor/plugins/active_merchant/lib/active_merchant/lib/connection.rb:60:in `request'
	from /var/www/html/dormbuys/vendor/plugins/active_merchant/lib/active_merchant/lib/connection.rb:136:in `retry_exceptions'
	from /var/www/html/dormbuys/vendor/plugins/active_merchant/lib/active_merchant/lib/connection.rb:54:in `request'
	from /var/www/html/dormbuys/vendor/plugins/active_merchant/lib/active_merchant/lib/posts_data.rb:43:in `ssl_request'
	from /var/www/html/dormbuys/vendor/plugins/active_merchant/lib/active_merchant/lib/posts_data.rb:26:in `ssl_post'
	from /var/www/html/dormbuys/vendor/plugins/active_merchant/lib/active_merchant/billing/gateways/authorize_net.rb:239:in `commit'
	from /var/www/html/dormbuys/vendor/plugins/active_merchant/lib/active_merchant/billing/gateways/authorize_net.rb:93:in `authorize'

I also tried to add new pem file under ssl_cert folder.
path: /usr/local/rvm/rubies/ruby-1.8.7-p374/lib/ruby/site_ruby/1.8/rubygems/ssl_certs/AddTrustExternalCARoot-2048.pem, but it didn't worked.

Please help me to resolve the issue.

**Comment by ntalbott** [comment]
@puneetimpinge ActiveMerchant doesn't support Ruby 1.8.7 any longer. You'll need to upgrade to a modern Ruby, preferably 2.0+, for us to be able to help you troubleshoot.
