### ISSUE TITLE
Credit card cleanup disallows client-side encryption (Braintree-style)

### ISSUE THREAD

**Issue by hult** [activemerchant/active_merchant#1771]
In 077a2216064438c69703d777f2d6312edce7cfd1, credit card numbers are cleaned up on assignment. Problem is, that breaks client-side encryption schemes (in my case Braintree).

Since before (in 1.42.9 for example), we've always done this (number and all other fields are values encrypted client-side and just forwarded to Braintree):

```
credit_card = ActiveMerchant::Billing::CreditCard.new(number: "$bt4|ios_2_2_4$X09HCFJ3dQTJKZeXeXOC1JsquHCwv5phDEfBmD8X3mBCafzyNKnTuRf88eRXfq9qLltMn181xQmf52hIuPCZtVmzFJ677SpX12LBt+7KF15\/M8V2W3Ehb7irB4gIfdXCBdkhsEMEd9cWf7rLAvbN4Wpc6JQ0IBQWZGcb0I9eTT9Ua9s8jlt3+kCk0qWH\/pu2rnTrYGGmZvmli0WegNnLub+\/QbMr4c5PGHvCeOm6gFYcKPgzHQx0RkOsdmuyEIFMo+JhjWf1EVWxJVH9i\/iMrRe2njX+ry2U\/IrqNJki77RJDBB\/T68272VlKRxTIY8KvNHNJ\/3qE8Or4JCkxuDYgg==$EzdL3bd3QEBwKSCal38AAIO21srpp++n4u8JH2CGaOQSqtp7ThPmuznJ3Iwec3FP$RZIVRoj6kq0zJpWdPb20IDlwaPUA3FqrOnqC5vybXhI=", ...)
my_gateway.store(credit_card)
```

But that is no longer possible because the number is cleaned up at assignment. Is this intended behavior? If so, what's the way of getting this to work now?

**Comment by bpollack** [comment]
This issue is almost three years old with no followup and no movement; closing. Please reopen if this is still an issue for you.

**Comment by yuhonas** [comment]
I ran into this one as well using `ActiveMerchant::Billing::EwayRapidGateway`

Eway also has a [client side encryption](https://eway.io/api-v3/#client-side-encryption) to limit PCI DSS exposure

It looks like there's no way to opt out of the filtering as far as I can see

https://github.com/activemerchant/active_merchant/blob/af6cd39c4e13dea1fd2960f62f33818fd62ae873/lib/active_merchant/billing/credit_card.rb#L88-L90

Could we perhaps add an additional class variable as is done with these 

[require_name/require_verification_value](https://github.com/activemerchant/active_merchant/blob/af6cd39c4e13dea1fd2960f62f33818fd62ae873/lib/active_merchant/billing/credit_card.rb#L80C1-L81)

eg. `self.perform_number_filtering = true` so it's a non breaking change

Then we could at least opt out by setting `ActiveMerchant::Billing::CreditCard.perform_number_filtering = false` for the exceptions like these

open to ideas! or to put up a PR if there's some consensus

**Comment by hult** [comment]
@yuhonas Sorry to say this project was canceled not long after this, and we never upgraded from 1.42.9, so we never solved it. :/
