### ISSUE TITLE
Request data

### ISSUE THREAD

**Issue by willian** [activemerchant/active_merchant#1791]
Hello!
From a client: "Is there a way to get the raw request data that is sent to the gateway? if not, are there any work around to get the raw request data?"

He wants to know what data ActiveMerchant is sending to gateways.

Thanks,

**Comment by girasquid** [comment]
Yes - set `wiredump_device` on the instance of an `ActiveMerchant::Billing::Gateway` to a variable, and then log that after you have made your calls.

You can see this being used to generate the transcript to use for implementing scrubbing in new gateway implementations here: https://github.com/activemerchant/active_merchant/blob/a3b531bd8d1de4cd9d83b30e816e1fac78592102/generators/gateway/templates/remote_gateway_test.rb#L127-L145, https://github.com/activemerchant/active_merchant/blob/a3b531bd8d1de4cd9d83b30e816e1fac78592102/test/test_helper.rb#L268-L285.

**Comment by willian** [comment]
Thank you @girasquid, I will test it :)
