### ISSUE TITLE
Authorize.net new urls

### ISSUE THREAD

**Issue by avdmatamoros** [activemerchant/active_merchant#1793]
We have received an email from authorize.net indicating that they will be changing their api access urls and moving some infrastructure to Akamai.

Here is the relevant section from the email:

The new Akamai transaction URLs that are available now are:

https://api2.authorize.net/xml/v1/request.api
https://api2.authorize.net/soap/v1/Service.asmx
https://secure2.authorize.net/gateway/transact.dll
Please contact your web developer or solution provider for assistance in updating to one of these new Akamai URLs.

Therefore these new urls will need to be set in the authorize.net gateway file

**Comment by girasquid** [comment]
This was taken care of in https://github.com/activemerchant/active_merchant/commit/64034cfd64ea20cc327c5ce6251522ec539b79b1.
