### ISSUE TITLE
Authorize.Net Networking Change

### ISSUE THREAD

**Issue by ashutosh413** [activemerchant/active_merchant#1796]
Dear Active Merchant Developers,

I have used ActiveMerchant Gem in my project for using AuthorizeNetCIM services. And I got following mail about the some updates from Authorize.net. I want to know have you managed these requirements on not. Do I need to change something in my application or not. Please review the mail attached below. 
 

 
 

Important Authorize.Net Networking Change
 
Dear Authorize.Net Developer:
 
At Authorize.Net, the reliability of our platform is our first priority. Your business and your merchants' businesses depend on our services, and we understand how important that is. To that end, we are implementing a new networking solution that will provide merchants with a superior level of processing reliability.

Please read this email thoroughly.

Akamai Network Technology
Over the coming months, Authorize.Net will be upgrading access to the Internet connections that serve our data centers. Instead of allowing direct connections, all Internet traffic will be routed through Akamai, a third-party cloud network service that routes and delivers Internet traffic.

Using Akamai network technology will help decrease latency and improve the reliability of our payment gateway. It will also help safeguard against interruptions caused by issues beyond Authorize.Net's direct control, such as Internet congestion, fiber cable cuts and other similar issues. Additionally, come October, merchants connected to Akamai should no longer be affected by planned downtimes.

Implementation Plan And Timeline
We are implementing Akamai's technology into our network in two phases.

Phase One (Now through June 2016) — We have created three new URLs for transaction processing that are hosted by Akamai. You can update your website or payment solution to point to the new transaction URLs today, which will provide the immediate benefits detailed above. Come October, merchants connected to Akamai should no longer be affected by planned downtimes.
Phase Two (June 2016) — We will automatically direct all of our existing transaction processing URLs to connect through Akamai in June of 2016. After this change, all transaction URLs will connect to Authorize.Net through Akamai.
IMPORTANT: To take advantage of the uptime benefits Akamai offers, we recommend you proactively update your website or payment solution during Phase One rather than waiting to be automatically updated during Phase Two.

Updating Your Solution
The new Akamai transaction URLs that are available now are:

https://api2.authorize.net/xml/v1/request.api
https://api2.authorize.net/soap/v1/Service.asmx
https://secure2.authorize.net/gateway/transact.dll
We will begin sending our initial emails about Akamai to merchants starting tomorrow.

Firewall And IP Address Considerations
If you do not use a firewall or do not connect directly via an IP address, then you can disregard this section.

Using Akamai technology, Authorize.Net's IP addresses will become dynamic rather than static. If your website or payment solution uses a firewall that has whitelisted Authorize.Net's IP address or connects to Authorize.Net directly via an IP address, you will need to make additional changes.

Firewall Considerations — If your solution uses a firewall to filter outbound connections, make sure that the firewall is set to permit outbound traffic to flow to the Akamai cloud by configuring your outbound firewall to "ANY." 
If you do not update your firewall ahead of June 2016, you will be unable to process transactions after Phase Two is implemented.
IP Address Considerations — If your solution connects to Authorize.Net directly via an IP address, you will need to update it to connect by domain name. Continuing to connect directly via an IP address is strongly discouraged as merchants will not receive the benefits of routing through Akamai, and could suffer a loss of service if transactions are re-routed among our various data centers.
Akamai is available for testing now in our sandbox environment. We strongly encourage you to test your solution prior to making any production change to ensure that you will not experience any disruptions to transaction processing.

Questions?
If you have any questions about the Akamai upgrade, please refer to our Akamai FAQs or contact Developer Support.

Thank you for your attention to this important email. We appreciate your ongoing partnership and are excited to bring you the benefits and reliability that this enhanced service provides.

Sincerely,
Authorize.Net

Related Links
Akamai FAQs
Developer Support
 
Authorize.Net
Authorize.Net
Authorize.Net
 
 
 
This email has been sent to  jlewis@fairhealth.org. 
 
You received this email because you are registered user or partner of Authorize.Net. Click to unsubscribe from future emails. 

For information on Authorize.Net communications and how we handle customer information, please see our Spam Policy and Privacy Policy. Please do not reply to this email.

© Copyright 2015. Authorize.Net, a CyberSource solution. P.O. Box 8999, San Francisco, CA 94128-8999. All other marks are the property of their respective owners. All rights reserved. 
http://app.payment.authorize.net/e/FooterImages/FooterImage1?elq=eaece658af17427cbd49a797166d173f&siteid=986383348

**Comment by Debadatta** [comment]
We have used activemerchant in our application. 

We checked in github repository file https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/authorize_net_cim.rb

for AuthorizeNetCimGateway.live_url = 'https://api2.authorize.net/xml/v1/request.api'

But when we upgraded gem 'activemerchant', activemerchant (1.51.0) installed properly, 

But still the AuthorizeNetCimGateway.live_url = 'https://api.authorize.net/xml/v1/request.api'

Please let us know what changes need to do for our application .

**Comment by girasquid** [comment]
I've released version 1.52.0 - if you update your gem version you'll get the new URLs.

**Comment by brandoncc** [comment]
@girasquid  I'm working with a Rails 2.3.18 application on Ruby 2.1. Is 1.52.0 compatible with Rails 2.3.18? I suspect not, but I would like to test/switch-to these urls in my application now before time runs out to fix issues if they arise. If it is not compatible, do you have a recommendation on how to do this beside altering a local copy of the gem and running it that way?
