### ISSUE TITLE
API url for akamai changes not reflecting in latest gem version

### ISSUE THREAD

**Issue by Debadatta** [activemerchant/active_merchant#1797]
We have used activemerchant in our application. 

We checked in github repository file  https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/authorize_net_cim.rb

for ``AuthorizeNetCimGateway.live_url = 'https://api2.authorize.net/xml/v1/request.api'``

But when we upgraded ``gem 'activemerchant'``, ``activemerchant (1.51.0)`` installed properly, 

But still the ``AuthorizeNetCimGateway.live_url = 'https://api.authorize.net/xml/v1/request.api'``

Please let us know what changes need to do for our application .

**Comment by girasquid** [comment]
I've released version 1.52.0 - if you update your gem version you'll get the new URLs.
