### ISSUE TITLE
firstdatae4 V14

### ISSUE THREAD

**Issue by wedstar** [activemerchant/active_merchant#1801]
Hi guys, any plans to support firstdatae4 v14 or anyone is doing it at the moment?
starting with v12, user needs to generate a hash and submit this in the headers
im happy to contribute if none

**Comment by wedstar** [comment]
hi @jnormore, i grabbed your name from first_data's contributor list, i was wondering if you could help me with this question above, thank you.

**Comment by andrewpaliga** [comment]
@wedstar no one is working on this on our end at the moment, contributions would be welcomed.

**Comment by wedstar** [comment]
thank you @andrewpaliga 
i have created a PR for this, https://github.com/activemerchant/active_merchant/pull/1824 
im closing this issue now
