### ISSUE TITLE
Transfirst purchase not working with ActiveMerchant

### ISSUE THREAD

**Issue by amitrmohanty** [activemerchant/active_merchant#1802]
I am stuck by getting the following error, NEED SOME URGENT ATTENTION

/home/vagrant/.rvm/gems/ruby-2.0.0-p598@leaguer3/gems/activemerchant-1.51.0/lib/active_merchant/posts_data.rb:79:in `handle_response': Failed with 500 Internal Server Error (ActiveMerchant::ResponseError)

Here my code snippets:
```ruby
require 'rubygems'
require "active_merchant"
require 'active_merchant/billing/rails'
ActiveMerchant::Billing::Base.mode = :test
gateway = ActiveMerchant::Billing::TransFirstGateway.new(
    :login    => 'XXXXXXXXXXXXXXXXXXXXXX',
    :password => 'XXXXXX'
)
amount = 1000
credit_card = ActiveMerchant::Billing::CreditCard.new(
                :first_name         => 'Bob',
                :last_name          => 'Bobsen',
                :number             => '5454545454545454',
                :month              => '1',
                :year               => Time.now.year+5,
                :verification_value => '988')
if credit_card.validate.empty?
  puts "0------going to purchase"
  response = gateway.purchase(amount, credit_card)

  if response.success?
    puts "Successfully charged $#{sprintf("%.2f", amount / 100)} to the credit card #{credit_card.display_number}"
  else
    # raise StandardError, response.message
    puts "------error"
    p response.message
  end

end
```

**Comment by girasquid** [comment]
That error gets raised when the gateway you're talking to throws a 500 error - you'll need to get in touch with them to figure out why that's happening and whether that's something they should be fixing on their end, or if something is being formatted/translated incorrectly in ActiveMerchant.

**Comment by andola-dev** [comment]
Thanks for reply. I know this earlier. But I need to know from which source the error is captured. whether it's an issue from active merchant or transfirst.

Your reply is not sufficient to make this ticket close.

**Comment by girasquid** [comment]
The `ResponseError` is being raised because the response coming back to you from Transfirst is something that ActiveMerchant doesn't know how to handle: https://github.com/activemerchant/active_merchant/blob/912f0760df2c2023663e87d9c8471d4f1d4f921d/lib/active_merchant/posts_data.rb#L79.

**Comment by andola-dev** [comment]
active_merchant/lib/active_merchant/billing/gateways/trans_first.rb
line no: 4
self.live_url = self.test_url = 'https://webservices.primerchants.com/creditcard.asmx/CCSale'

Do you think end point should be same for live and test?

**Comment by girasquid** [comment]
I'm not familiar enough with the Transfirst integration to say; try asking them?
