### ISSUE TITLE
Elavon - Send cardholder's IP on purchase and authorization

### ISSUE THREAD

**Issue by cjoudrey** [activemerchant/active_merchant#1822]
We are currently not sending the cardholder's IP when performing an auth or sale.

[According to the docs](https://www.myvirtualmerchant.com/VirtualMerchant/download/developerGuide.pdf) this can be done by passing `ssl_cardholder_ip`.

It should be an easy fix that we can do in [`def purchase`](https://github.com/activemerchant/active_merchant/blob/2897332fc998309683558874840767253389db68/lib/active_merchant/billing/gateways/elavon.rb#L72) and [`def authorize`](https://github.com/activemerchant/active_merchant/blob/2897332fc998309683558874840767253389db68/lib/active_merchant/billing/gateways/elavon.rb#L94).

Example of another gateway that passes IP: https://github.com/activemerchant/active_merchant/blob/2897332fc998309683558874840767253389db68/lib/active_merchant/billing/gateways/iats_payments.rb#L80-L83

cc @shawnfrancis

**Comment by shawnfrancis** [comment]
My client wrote me an email on the Evalon integration:

Shawn, also noticed one of their other Payment Gateway filters won't work - looks like Billing Address Country doesn't flow through from Shopify to Elavon on transactions (Country looks like it's left blank), so any fraud filter people would setup to restrict customers with certain Billing Countries will automatically decline every credit card transaction that comes through.

The last part to verify is if CVV2 and AVS codes pass through correctly from Shopify.

Sorry about all this - it looks like Elavon isn't setup to be a suitable Payment Gateway for Shopify.

**Comment by jordanliddle** [comment]
@cjoudrey I'll look at setting this up today
