### ISSUE TITLE
Active Merchant Truck Factor

### ISSUE THREAD

**Issue by gavelino** [activemerchant/active_merchant#1838]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Active Merchant** and obtained a value of **6**.

The developers responsible for this TF are:

Cody Fauser - author of 36% of the files
Nathaniel Talbott - author of 20% of the files
Duff OMelia - author of 6% of the files
Mark Bennett - author of 4% of the files
Dennis Theisen - author of 2% of the files
John Duff - author of 2% of the files

To validate our results, we would like to ask **Active Merchant** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Active Merchant**?

(b) Do you agree that **Active Merchant** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Active Merchant** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by aprofeit** [comment]
I'm not sure a github issue is the best way to collect this info, but for what it's worth:

a) No. 3 of them no longer actively work on the project.
b) It would be less maintained if two of them left.
c) It's fairly simple to understand and get up to speed by just reading the code.
