### ISSUE TITLE
Offsite payments 

### ISSUE THREAD

**Issue by piotr-galas** [activemerchant/active_merchant#1850]
Is it possible to contribute "my custom" offsite payment to active-merchant? My customer ask me about it. His payment is already added to 

https://github.com/activemerchant/offsite_payments

I just want to make sure that you remove offsite paymant and now it is not possible.

**Comment by ntalbott** [comment]
@piotr-galas active_merchant is only for direct API gateways; if it's an offsite flow, it only goes in offsite_payments. Hope that helps clarify!
