### ISSUE TITLE
Adding another gateway

### ISSUE THREAD

**Issue by cyber2001** [activemerchant/active_merchant#1857]
Hi, sorry for creating an issue.
I wanted to add a new gateway that is a little different. In my country(Iran) there is a website that provides transactions based on Iranian money(Rials). The website is working with soap method in two calls[requestpayment, verification].
is there any way to add this gateway to this gem? thanks.

**Comment by ntalbott** [comment]
@cyber2001 does the SOAP API accept credit card information directly?

**Comment by cyber2001** [comment]
No, there is no credit card in this website.
the code is:
```
require 'savon'

module Jpay

  def self.request_payment(amount, callback, order_id, text)
    api = Rails.application.config.jpay_api
    info = {api: api ,amount: amount, callback: callback, orderid: order_id, txt: text }
    client ||= Savon.client(wsdl: 'http://www.jahanpay.com/webservice?wsdl')
    res=client.call(:requestpayment, message: info)
    if res.body[:requestpayment_response] and res.body[:requestpayment_response][:return]
      code = res.body[:requestpayment_response][:return]
      code
    end
  end
  
  def self.response(amount, auth)
    api = Rails.application.config.jpay_api
    info = {api: api ,amount: amount, authority: auth}
    client ||= Savon.client(wsdl: 'http://www.jahanpay.com/webservice?wsdl')
    res=client.call(:verification, message: info)
    if res.body[:verification_response] and res.body[:verification_response][:return]
      code = res.body[:verification_response][:return]
      code
    end
  end

end
```
the `info` hash contains the items required by the website.
after the transaction, the website deposits the amount in my site account, when I ask for money, the deposit it to my real account in any bank in Iran.

**Comment by ntalbott** [comment]
@cyber2001 it doesn't sound like a good fit for ActiveMerchant, which is focused on direct API's that take credit card (and to a lesser degree, bank) information. Maybe it would be a fit for https://github.com/activemerchant/offsite_payments?
