### ISSUE TITLE
guidance regarding adding new gateway

### ISSUE THREAD

**Issue by avenuestest** [activemerchant/active_merchant#1860]
@ntalbott

i need to add new gateway to Shopify. 

Flow of gateway is like customer hits checkout on merchants shopify website. Then customer is redirected to payment gateway website. Customer will fill  payment information and do payment. Customer will see payment result successful or failed and customer will be redirected to merchants shopify website. 

Dose adding gateway to Activemerchant, will it support redirection from shopify to payment gateway and again back to shopify. Or is there any other way to add redirected gateways to shopify.

i have added code and created pull request as " Adding CCAvenue Payment gateway #1858 "

please give your suggestions

**Comment by girasquid** [comment]
Redirect-style integrations live in our https://github.com/activemerchant/offsite_payments repository, but the addition of your gateway to offsite_payments *does not guarantee integration with Shopify*. If you'd like to integrate with Shopify, send an email to payment-integrations@shopify.com with *Offsite Payments Integration* in the subject and include:

- Name, URL & description of the payment provider you wish to integrate
- Markets served by this integration
- List of major supported payment methods
- Your most recent Certificate of PCI Compliance
- Reason that the [Universal API](https://github.com/activemerchant/offsite_payments/blob/master/lib/offsite_payments/integrations/universal.rb)* cannot be used for your integration.

*The Universal API defines a standard set of requests and callbacks that can be used to integrate with Shopify. A sample app and documentation are hosted here. The Universal API should be used for all integrations in which placement within Shopify is the desired outcome.
