### ISSUE TITLE
Can't process ECC (unlinked) refunds with Authorize.net via CIM 

### ISSUE THREAD

**Issue by steakchaser** [activemerchant/active_merchant#1863]
_Using ActiveMerchant 1.52.0_

Expanded Credit Capabilities [ECC](https://www.authorize.net/support/CP/helpfiles/Miscellaneous/Pop-up_Terms/Expanded_Credit_Capabilities.htm) allows you to process refunds for transactions that either occurred over 120 days ago or were not processed through the payment gateway.

In order to process these types of refunds you must [request ECC capabilities](http://www.authorize.net/files/ecc.pdf) from Authorize.net.

Once setup you need to submit refund requests without the `transId` parameter.  `AuthorizeNetCimGateway` will currently add this to all refund requests, even if it's not passed in by the client.  See the `add_transaction` `:refund` case:

`xml.tag!('transId', transaction[:trans_id])`

This could probably be fixed one of two ways:
1. Set `transId` as an optional tag
2. Create a new `CIM_TRANSACTION_TYPES` so that processing drops down to the `else` case where `transId` is already not set.

**Comment by ntalbott** [comment]
@steakchaser the `AuthorizeNetCimGateway` is on its way to deprecation, so the maintainers are not really motivated to make further improvements to it. Going forward, the CIM functionality is integrated directly into the `AuthorizeNetGateway` class via the ActiveMerchant-standard `store`/`update`/etc. API.

I'd suggest adding this ECC capability to the `AuthorizeNetGateway#credit` method, if it doesn't already support it. We'll do our best to review a PR that adds the functionality there.

**Comment by steakchaser** [comment]
@ntalbott `credit` does not appear to support CIM.  

Would you prefer a PR that updates `credit` to support CIM and ECC?  Or, a PR that just updates `cim_refund` to support ECC?

**Comment by ntalbott** [comment]
@steakchaser the former would be best; the latter could potentially get merged, but will then just get removed when the CIM-specific gateway is removed, so doesn't seem worth your time.

**Comment by steakchaser** [comment]
@ntalbott just to clarify `cim_refund` is actually in `AuthorizeNetGateway` (not the deprecated one).  The `cim`* methods are used if the action starts with "cim".  In `refund` for example: 

````
      def refund(amount, authorization, options={})
        if auth_was_for_cim?(authorization)
          cim_refund(amount, authorization, options)
        else
          normal_refund(amount, authorization, options)
        end
      end
````

**Comment by ntalbott** [comment]
@steakchaser oh, funny - guess I should have checked the code :grin:

So what we really need here is a `cim_credit` in that case, since `credit` is the API method that ActiveMerchant uses for "unreferenced refunds", which is what ECC is, right?

**Comment by steakchaser** [comment]
@ntalbott Correct, ECC is unreferenced funds.  OK sounds good, I'll work on a PR soon.  Thanks.

**Comment by kate008** [comment]
I would like to use CIM method for refund transaction using the transaction Id.Can anyone help how to build the xml request and what params needed to make Refund Transaction ?
