### ISSUE TITLE
Gift Card Balance

### ISSUE THREAD

**Issue by tedma4** [activemerchant/active_merchant#1895]
Sorry for posting this here but I can't seem to find the answer anywhere. I have to use this gem in a code challenge and was wondering if you could point me in the right direction on this. I need to be able to show the remaining balance of a gift card. Is there a specific gateway that handles this? Or do I need to use another gem in conjunction with this one to handle this?

**Comment by ntalbott** [comment]
Checking gift card balances is outside of scope for ActiveMerchant, and I'm not aware of other libraries that handle it. Sorry!

**Comment by tedma4** [comment]
Ooops. Read the prompt wrong. Sorry. Thanks for getting back to me though.
