### ISSUE TITLE
FirstData E4 Forgets Credentials (Local)

### ISSUE THREAD

**Issue by marknfischer** [activemerchant/active_merchant#1915]
We are seeing very odd behavior in our app, where all gateways perform one way, but FirstData E4 is unique.  We can not reproduce it running active_merchant alone, so hoping someone has insight.  All integrations send gateway auth connections with each transaction, however FirstData E4 ONLY sends credentials on the first transaction.  Stopping subsequent transactions with binding.pry,... we can see that the request in active_merchant HAS the credentials, but they are not sent to E4 in the post.  Again, first transaction works, but every other transaction after that does not unless we restart our app.  Running ActiveMerchant in stand alone does not show this behavior.  Is there a specific flag in active_merchant to force it to "initialize" with the gateway as part of the communication for each transaction?  Why would this gateway be unique and NOT send initialization credential data on subsequent transactions when it does on the first and all other gateways always do?

**Comment by ntalbott** [comment]
@marknfischer we do a lot of FirstData E4 transactions here at Spreedly, and we've never seen this issue. Sounds like something locally is affecting things, which makes it pretty impossible for us as maintainers to provide input on what it might be. You could try asking on the [Google Group](https://groups.google.com/forum/#!forum/activemerchant), but I'm guessing you're just going to have to debug this locally. Sorry we can't offer more help. :cry:
