### ISSUE TITLE
Stripe - recurring payments

### ISSUE THREAD

**Issue by terleckijt** [activemerchant/active_merchant#1918]
Hi, I'm new to payment gateways, if anyone could help me with this I'd appreciate it alot.

![screen shot 2015-11-02 at 2 09 14 pm](https://cloud.githubusercontent.com/assets/15383084/10882480/5c611d06-816b-11e5-9520-c769c7ee2c65.png)

I have to change Authorize.net gateway to Stripe gateway, the problem is that ActiveMerchant doesn't have ACTIVE_MERCHANT_CIM equivalent for Stripe, the code I'm working on uses it extensively which is why I wouldn't want to get rid of ActiveMerchant and use plain stripe. Is there any way to switch between those gateways, without losing this functionality or breaking the rest of the code? Thank you for help in advance.

**Comment by ntalbott** [comment]
@terleckijt the `AuthorizeNetCimGateway` is actually deprecated in ActiveMerchant, so there isn't an upgrade path via ActiveMerchant for you. To get the recurring functionality that the CIM provides, you'll probably need to write it fresh against Stripe.
