### ISSUE TITLE
Are Redsys SHA256 changes supported?

### ISSUE THREAD

**Issue by josal** [activemerchant/active_merchant#1923]
Recently in Redsys we faced a warning in order to change the way to connect to our virtual point of sale.

Docs (spanish): https://canales.sermepa.es/canales/ayuda/migracionSHA256.html

Is it already supported or maybe I would have to create a pull request?

Thanks!!

**Comment by aprofeit** [comment]
Looks like this was added in https://github.com/activemerchant/active_merchant/pull/1927!
