### ISSUE TITLE
Ruby 1.9.3 OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by ss2k** [activemerchant/active_merchant#1933]
I know others have had similar issue but I can't seem to find any solution. I have tried everything I can think of.

This happens when I run the purchase method on the gateway object. Other https connections work fine from our app and its only with ActiveMerchant I have this issue.

Ruby Version: 1.9.3p550 (2014-10-27) [x86_64-linux]
OpenSSL Version: 1.0.1j 15 Oct 2014
Rails Version: 3.2.18
ActiveMerchant Version: 1.20.3

Unfortunately upgrading ruby/rails at this point is out of the question due to it causing so many other issues.

Any help appreciated.

**Comment by ntalbott** [comment]
@ss2k what gateway/host are you connecting to? How recent is your cert bundle?

Your OpenSSL version is pretty old; I'd try compiling Ruby with a more recent version like 1.0.1p for starters.

**Comment by ntalbott** [comment]
@ss2k also, while I don't mind helping you brainstorm some, it's important to note that ActiveMerchant claims no official support for Ruby < 2.0.

**Comment by ss2k** [comment]
I updated my ca cert bundle.
This is the response from my console:

irb(main):001:0> ENV['SSL_CERT_FILE']
=> "/etc/ssl/certs/ca-certificates.crt"
irb(main):002:0> cc = ActiveMerchant::Billing::CreditCard.new(...)
=> #<ActiveMerchant::Billing::CreditCard...>
irb(main):003:0> GATEWAY.purchase(100, cc)
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

**Comment by ntalbott** [comment]
@ss2k did you re-compile Ruby against the upgraded OpenSSL? It's a native extension, so generally won't pick up package upgrades until you re-compile. There's also some way within Ruby to check what version of OpenSSL it's compiled with.

**Comment by ss2k** [comment]
Hi,

I updated ruby to 1.9.3p547 after updating OpenSSL

**Comment by ntalbott** [comment]
Wow, didn't notice your ActiveMerchant version is so old. Can you try with
a newer version?

On Wednesday, November 18, 2015, SS <notifications@github.com> wrote:

> Hi,
>
> I updated ruby to 1.9.3p547 after updating OpenSSL
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/activemerchant/active_merchant/issues/1933#issuecomment-157896925>
> .
>


-- 
--
Nathaniel

**Comment by ss2k** [comment]
What's the latest version of ActiveMerchant that would support 1.9.3?

**Comment by ntalbott** [comment]
Not sure - you could check the commit history to see when we stopped
running the tests against 1.9.

On Wednesday, November 18, 2015, SS <notifications@github.com> wrote:

> What's the latest version of ActiveMerchant that would support 1.9.3?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/activemerchant/active_merchant/issues/1933#issuecomment-157915782>
> .
>


-- 
--
Nathaniel

**Comment by rafaelfranca** [comment]
@ntalbott maybe we should make that explicit and set the `required_ruby_version` in the gemspec? That way the gem is not installed with Ruby 1.9

**Comment by rafaelfranca** [comment]
Looks like the 1.47.0 is the latest version that support Ruby 1.9 https://github.com/activemerchant/active_merchant/commit/8a6c6ff626ebd292dc50e8e1c074aab49956a42d

**Comment by ss2k** [comment]
Thanks a lot. I will try to update to that and let you guys know what happens! I really appreciate the help.

**Comment by rafaelfranca** [comment]
PR updating the require ruby version to match our list of supported versions https://github.com/activemerchant/active_merchant/pull/1936

**Comment by ss2k** [comment]
Thanks guys. I think the 1.47.0 update worked!
