### ISSUE TITLE
How scrubbing is used?

### ISSUE THREAD

**Issue by alovak** [activemerchant/active_merchant#1939]
Hello! I see a lot of gateways have method to scrub sensitive data from logs. But I don't see who calls this method. Also scrub is an instance method. So it's not handy to use it let say in Logger.

Can someone help me to understand how this method is used or how it can be used to remove sensitive data from AM logs?

**Comment by girasquid** [comment]
It's used in conjunction with `wiredump_device`, like so:
```ruby
transcript = ''
gateway_instance = ActiveMerchant::Billing::Base.gateway('stripe').new(options)
gateway_instance.wiredump_device = transcript
# do some operations with the gateway_instance
gateway_instance.charge(..)
gateway_instance.refund(..)
# Dump a log of the entire HTTP conversation, with sensitive information scrubbed out
logger.info(gateway_instance.scrub(transcript)) if gateway_instance.supports_scrubbing?
```

**Comment by alovak** [comment]
Thanks! Now it's more clear for me. I see that it does not work automatically when log level is debug as I expected it to be :)

**Comment by girasquid** [comment]
Ah, no - because you explicitly *need* to call `scrub` to have something that's safe to log, it's not turned on by default. It's a neat idea though..

**Comment by j-mutter** [comment]
That would be cool if every single gateway had a thorough `scrub` implementation...

PRs welcome :innocent:

**Comment by alovak** [comment]
What if we add something like this (raw solution):

```
module ActiveMerchant #:nodoc:
  module Billing #:nodoc:
    class Gateway
      # ...

      def logger
        @logger ||= LoggerWithScrubbing.new(ActiveMerchant::Billing::Gateway.logger, self)
      end

      class LoggerWithScrubbing
        attr_reader :logger, :gateway

        def initialize(logger, gateway)
          @logger, @gateway = logger, gateway
        end

        %w(info warn debug error).each do |method|
          define_method method do |string|                     # def info(string)
            logger.public_send(method, scrub(string))  #   logger.info filter_string(string)
          end                                                  # end
        end

        private

        def scrub(string)
          gateway.supports_scrubbing? ? gateway.scrub(string) : string
        end
      end
    end
  end
end
```

**Comment by alovak** [comment]
@girasquid @j-mutter what do you think?

**Comment by ntalbott** [comment]
@alovak my concern with this approach is that it implicitly passes non-scrubbed output to the logger when scrubbing is unimplemented. If we do automatic scrubbing, it would have to be in a way that errors if used against a non-scrubbing gateway.

**Comment by alovak** [comment]
@ntalbott not sure that I got your point (the last sentence) :)

now all output goes as is (without scrubbing) when log level is 'debug'. with this approach we only add protection to developers. Described above approach with ```wiredump_device``` will continue to work as is.

**Comment by alovak** [comment]
btw, we can implement default scrubbing method that will remove all card numbers (using basic regexp).

**Comment by j-mutter** [comment]
I think we tried a generic approach and it wasn't as simple as we had hoped, so we went with an explicit opt-in approach to simplify PCI compliance. It's been a while though, so maybe I'm forgetting something.

**Comment by alovak** [comment]
I can say for myself only. But after I add scrub method to gateway I expected to see filtered output in logs... Especially at the beginning we (maybe other startups and companies) set log level to debug to the whole system (all apps).

But explicit way is ok. Especially if you want to store gateway request/response in DB together with all other details.

**Comment by ntalbott** [comment]
Yes, scrub is specifically targeted at making transcripts safe for persistence. The advantage of opt-in is it that it makes the fact that not all transcripts are scrubbed explicit; my concern with automatic is that a developer could start with a scrubbed gateway and not realize that they're saving PCI data when they add a second gateway that is not scrubbed.

**Comment by alovak** [comment]
I see.

One solution it to output nothing if scrub method is not implemented:

```
def scrub(transcript)
  "Your logs can contain sensitive information that should be filtered. If you want to see log output for GatewayName please add scrub method as describe here: https://github/wiki/how_to_add_scrub_method"
end
```

Best practice for our area: block all. allow only what you really need :D

**Comment by ntalbott** [comment]
@alovak yah, but then if I do want log output for a gateway that doesn't support scrubbing, how do I get it?

**Comment by alovak** [comment]
the same as I have to do now to get it scrubbed...
```
transcript = ''
gateway_instance = ActiveMerchant::Billing::Base.gateway('stripe').new(options)
gateway_instance.wiredump_device = transcript
# do some operations with the gateway_instance
gateway_instance.charge(..)
gateway_instance.refund(..)
# Dump a log of the entire HTTP conversation, with sensitive information scrubbed out
logger.info(transcrip)
```

no?

**Comment by alovak** [comment]
Ok. I don't see a beautiful solution. It's a trade off. If nobody asked for this before then maybe there is no issue with this at all.

At least I was able to fix it for myself (with offered solution).

**Comment by ntalbott** [comment]
It's great feedback! I'll keep it in mind. Ideally we would just make `scrub` required and backport it to all adapters, but we're not there yet.
