### ISSUE TITLE
JPY Conversion Inconsistencies

### ISSUE THREAD

**Issue by datibbaw** [activemerchant/active_merchant#1943]
We're using the `CybersourceGateway` class to do reverse authorisation and sales in our system; the problem we've encountered, which is related to #1794, is that when we try to reverse an authorisation made in JPY the `amount()` method will do a dumb division by 100.

I can make this work by doing the same kind of dumb multiplication, but by doing so I might break another gateway, e.g. Sage that uses `localized_amount()`.

My issue is therefore: I don't know how to properly solve this issue on our side :(

Your insight would be greatly appreciated!

**Comment by porty** [comment]
I can confirm that PayPal purchases work as intended, but PayPal refunds are broken because amount is divided by 100

**Comment by bpollack** [comment]
@datibbaw I _think_, based on reading current Cybersource code, that this shouldn't still be happening; are you still seeing it?

**Comment by bayprogrammer** [comment]
I believe this was corrected by #2186.
