### ISSUE TITLE
authorize_net gateway confusing money_format

### ISSUE THREAD

**Issue by dikond** [activemerchant/active_merchant#1949]
Hi to everyone
I am using activemerchant 1.52.0 and two gateways: _AuthorizeNetGateway_ and _AuthorizeNetCimGateway_

I've expected that their money format would be identical, e.g. both in dollars. But it seems like _AuthorizeNetGateway_ using cents formatting, however [13th line](https://github.com/activemerchant/active_merchant/blob/master/lib%2Factive_merchant%2Fbilling%2Fgateways%2Fauthorize_net.rb#L13) indicates dollars formatting. I found it confusing... 

Should _AuthorizeNetGateway_ format actually in dollars? If not, I can just fix that 13th line.

**Comment by ntalbott** [comment]
Danny, the key thing is that you should always provide amounts to ActiveMerchant in cents. It then takes care of transforming that amount to the right format for the given gateway.

Both the `AuthorizeNet` and `AuthorizeNetCim` gateways are super battle-tested, so you can be confident that they're doing that process correctly for you.

**Comment by dikond** [comment]
@ntalbott thanks for fast reply!
However `create_customer_profile_transaction` under the CIM gateway takes amount in decimal, not in cents. That's why I wrote it - because I've used the same amount for these two gateways, but authroize.net charged different amounts.

**Comment by ntalbott** [comment]
@dikond so the standalone CIM gateway in ActiveMerchant is deprecated and will be removed in a the next major revision. We'll merge a PR to fix this issue if you submit one - assuming you include a working remote test showing the issue - but I'd recommend not using the gateway in the first place.

**Comment by dikond** [comment]
@ntalbott why it is deprecated? And what would you recommend to use for storing the card? I saw there is an official ruby sdk from authorize.

**Comment by ntalbott** [comment]
@dikond it's deprecated since the adapter API is completely non-standard for ActiveMerchant. If you want to use ActiveMerchant, and your CIM needs are straightforward, you can use the `AuthorizeNetGateway#store` method. If you have more complicated needs, I'd look at an Auth.Net specific gem, or just hit their API directly.
