### ISSUE TITLE
Unable to pass basket field via Sagepay gateway

### ISSUE THREAD

**Issue by ums-uk** [activemerchant/active_merchant#1957]
Sagepay v3 provides the ability to pass the basket field through to the payment gateway so that they can be imported into Sage. I cannot see in the code a way to pass this field from my app through to the gateway.

Details on basket field is available here: https://www.sagepay.co.uk/support/28/37/items-not-deducting-from-your-stock

Thanks

**Comment by ntalbott** [comment]
@ums-uk this is generally outside of scope for ActiveMerchant, but we're willing to consider a Pull Request that passes gateway specific fields like this through the `options` hash. You can look through other adapters in ActiveMerchant for examples on how line items are handled when they're supported.
