### ISSUE TITLE
Question on `response.success?`

### ISSUE THREAD

**Issue by bruno** [activemerchant/active_merchant#1971]
I've just noticed, as we were testing, that for the Fat Zebra payment gateway, that in the case of a declined payment, the `success_from(response)` method which is used in:

```Ruby
success = success_from(response)
        Response.new(
          success,
```

for the response, is returning `nil` instead of `false` or `true` ... is it an expectation that this can be `nil` ... ? If that's the case with other gateways, then I will build our downstream methods to be ready to expect `nil` ... as well as `false` or `true` ... Just asking to understand the guidelines ... if it's meant to _always_ be either `true` or `false` I will submit a patch  / pull request ...

**Comment by ntalbott** [comment]
@bruno we fully embrace Ruby's notion of truthiness, so `nil` is a fine value for `success?` and should be treated the same upstream as `false`.

**Comment by bruno** [comment]
Thank you @ntalbott
