### ISSUE TITLE
PayflowGateway Currency Coversion Problem

### ISSUE THREAD

**Issue by HassanAkbar** [activemerchant/active_merchant#1981]
`response = gateway.authorize(100, credit_card,{ currency: 'EUR')}`

This surely changes the currency of payment.

However when I use `pn_ref` instead of credit_card number the transaction appears as 'USD' .

`response = gateway.authorize(100, pn_ref,{ currency: 'EUR' })`

**Comment by bpollack** [comment]
I don't see that behavior here, but we'd be really happy to accept a PR (or even a test case for the remote suite that shows this behavior happening)!
