### ISSUE TITLE
Tests Fail against BraintreeBlue on missing authorization 

### ISSUE THREAD

**Issue by raymondberg** [activemerchant/active_merchant#2005]
We noticed a commit that causes failing builds against a BraintreeBlue gateway. The two lines causing this issue were commented: [line 578](https://github.com/activemerchant/active_merchant/commit/982eaea5819814f6f3deab84357e7dfddc2ae309#diff-d3e31ce1d7cbbc102d604bd1b6642dc2R578) and [line 412](https://github.com/activemerchant/active_merchant/commit/982eaea5819814f6f3deab84357e7dfddc2ae309#diff-d3e31ce1d7cbbc102d604bd1b6642dc2R412) from commit 982eaea5819814f6f3deab.

**Comment by pblesi** [comment]
@prburke A month ago you added a commit that has improper assumptions about the way our client library works. Can you make an update to remove the invalid assertions?

**Comment by prburke** [comment]
Done...#2039.  My apologies, I missed the original comments.

**Comment by davidsantoso** [comment]
Closing since it seems the associate PR was merged.
