### ISSUE TITLE
ActiveMerchant doesn't work with JRuby?

### ISSUE THREAD

**Issue by aldrinkyck** [activemerchant/active_merchant#2011]
So installed active_merchant through bundler. I had some time spent trying to figure out which activemerchant version will work with jruby since the latest gem require ruby 2.0 and above. I'm using jruby-1.7.13 with rails 3.2.18. Now this is what's happening when I try to start the rails console:

Bundler::GemRequireError: There was an error while trying to load the gem 'activemerchant'.
  require at /Users/username/.rvm/gems/jruby-1.7.13@kyck_registrar_web/gems/bundler-1.11.2/lib/bundler/runtime.rb:81
     each at org/jruby/RubyArray.java:1613
  require at /Users/username/.rvm/gems/jruby-1.7.13@kyck_registrar_web/gems/bundler-1.11.2/lib/bundler/runtime.rb:72
     each at org/jruby/RubyArray.java:1613
  require at /Users/username/.rvm/gems/jruby-1.7.13@kyck_registrar_web/gems/bundler-1.11.2/lib/bundler/runtime.rb:61
  require at /Users/username/.rvm/gems/jruby-1.7.13@kyck_registrar_web/gems/bundler-1.11.2/lib/bundler.rb:99
   (root) at /Users/username/workspace/kyck_registrar_web/config/application.rb:10
  require at org/jruby/RubyKernel.java:1065
   (root) at /Users/username/.rvm/gems/jruby-1.7.13@kyck_registrar_web/gems/railties-3.2.18/lib/rails/commands.rb:1
  require at org/jruby/RubyKernel.java:1065
   (root) at script/rails:6

I'm not really sure what to do with this since a quick google search didn't really return any results.

**Comment by ntalbott** [comment]
@aldrinkyck I don't think any of the maintainers use JRuby with ActiveMerchant, so you're kind of on your own here.

**Comment by sybind** [comment]
+1

**Comment by chrismo** [comment]
fwiw, hitting something similar now with jruby 1.7.16.1 and activemerchant 1.44.1 and OS X version 10.12 - last time I worked with this repo, I was an older version of OS X ... getting up to activemerchant 1.55.0 allowed me to get past the problem.

Problem though had different symptom, simply getting bundler (versions 1.11, 1.13 and 1.14) hanging when trying to `bundle` on an existing install after 'Using activemerchant 1.44.1`.

**Comment by chrismo** [comment]
nevermind - i think this is completely unrelated. looks like activemerchant was just the last gem installed, and bundler was actually hung doing something after installing all the gems.
