### ISSUE TITLE
activemerchant contains also activeshipping?

### ISSUE THREAD

**Issue by megetron** [activemerchant/active_merchant#2014]
Hi there,
I am using application which use active_shipping gem. I would like to add the support of the active_merchant for a gateway system. 

should I remove from my application the active_shipping gem and use it through the active_merchant gem?

**Comment by timbeiko** [comment]
Accidentally closed instead of https://github.com/activemerchant/active_merchant/commit/b0eb93a166273f6c0e8ebdb5a473f514c05cd65c . Re-opened.

**Comment by Amritpal363** [comment]
Good morning  🙏🌹india punjabi city code 143604

![Image](https://github.com/user-attachments/assets/ffe19dc9-5598-4f1e-a857-bcdf03093bc1)
