### ISSUE TITLE
Migs Error

### ISSUE THREAD

**Issue by joeblack81** [activemerchant/active_merchant#2018]
Hi, I am using Migs gateway , but I am not abel to redirect the client to mastercard site so he can put his data and return back to my site, can @mnoack  explain to me please how to do it .

Thanks a lot 
Joe

**Comment by mnoack** [comment]
@joeblack81 firstly, offsite payments (you said redirect) is best done using the activemerchant/offsite_payments project, we have submitted a PR to that project. See: https://github.com/activemerchant/offsite_payments/pull/187

Once this was merged I was actually going to PR to remove this part of MiGS from activemerchant.

We are using the offsite_payments code in production and have tested it extensively.

The specs in that Pull Request I think explain how to use it very well, but if you have further questions feel free to ask.

**Comment by joeblack81** [comment]
@mnoack , Thank you so much for your quick reply, I am new to rails so excuse my silly questions,
Now I am able to get redirected to Migs server using the credentials and secure hash in the test class as following :
 options = {
     :order_id   => 1,
     :unique_id  => 9,
     :return_url => 'http://localhost:3000/payments/returnurl'
    }
   
     @amount = 100
     redirect_to @gateway.purchase_offsite_url(@amount, options)

But when I use my credentials that i got from my provider , I get this error:
Secure Hash mismatch, response may be tampered with

How can I create my secure Hash?, How can I verify the response coming from Migs server to make sure that no one playing around?

Thanks and best regards

**Comment by mnoack** [comment]
The offsite_payments gem (in my PR) creates the secure_hash for you, and so does the old 'purchase_offsite_url' from activemerchant that you're using.

It's a required argument so I'm not sure why it's failing.

You need to give it the secure_hash when you initialize @gateway, this is what ANZ/CBA and other MiGS providers call secure_hash.

If you're still stuck you'll likely have to debug with something like pry-byebug or similar so you can go through the activemerchant code and look to see if any of these variables are odd (blank, etc.)

I also recommend trying offsite_payments (point to my branch as in the PR) as that's the code we currently use in production and I'm more familiar with that code so can help you more AND the code you're using will be deleted eventually anyway.

**Comment by joeblack81** [comment]
@mnoack  I want to use Migs in offsite_payments gem but I see that your code still not merged, how can I use it now?

**Comment by mnoack** [comment]
You can use sealink/offsite_payments (master branch)

**Comment by davidsantoso** [comment]
Closing due to staleness.
