### ISSUE TITLE
does 2checkout supported by active_merchant?

### ISSUE THREAD

**Issue by megetron** [activemerchant/active_merchant#2025]
this one is a very odd thing.
when I check shopify support for 2checkout payment gateway it exists.
but in active_merchant gem I can't find the support (and also couldn't find it in the git main page supported list).

can you please shade a light on this one?

**Comment by girasquid** [comment]
2checkout support is implemented in offsite_payments, here: https://github.com/activemerchant/offsite_payments/blob/master/lib/offsite_payments/integrations/two_checkout.rb.
