### ISSUE TITLE
CashNet seems to be double encoding some URL fields

### ISSUE THREAD

**Issue by sdball** [activemerchant/active_merchant#2031]
After the recent change to CashNet to encode the redirect URL it looks like passwords (and other credential fields?) are having double encoding issues.

```
password: "hello%^&"
original redirect url had: password=hello%25%5e%26
new encoded url has: password=hello%2525%255e%2526
```

I think it's due to some encoding happening within `ssl_post` and then the response comes back with a redirect that has the already encoded pieces which are then encoded again causing the credentials to fail.

**Comment by sdball** [comment]
Aha! There's some `CGI.escape` calls still in the gateway:

- https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/cashnet.rb#L61
- https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/cashnet.rb#L86

Since all the posted parameters are already encoded and are passed back in the redirect URL then encoding that redirect URL causes problems.

**Comment by rwdaigle** [comment]
@sdball given that the URL that's returned sometimes has non-URL safe characters, what are our options here? This seems like an issue that should be resolved at the gateway level (to not send back invalid URLs in the first place)?

**Comment by sdball** [comment]
Hmm, perhaps leaving the current escapes, splitting apart the redirect URL parameters, uneacaping them, then escaping the entire url?

What parts of the redirect URLs were unescaped before?

It sure sounds like a problem on their end to ensure they aren't sending invalid urls.

**Comment by rwdaigle** [comment]
@sdball here's the original issue: https://github.com/activemerchant/active_merchant/pull/1964

> Hmm, perhaps leaving the current escapes, splitting apart the redirect URL parameters, uneacaping them, then escaping the entire url?

So... no other options then :)

I think we need to roll this back, then. If Cashnet can't return valid URLs, and we can't escape their invalid URL because some of the params are already escaped, then we're in a bit of bind and shouldn't be expected to jump through hoops to debug-and-fix on the fly?

**Comment by ntalbott** [comment]
This is SO BIZARRE! So is the issue that we have params we have to escape before we pass them to Cashnet, and then they pass them back already escaped in a url we then need to escape again?

**Comment by sdball** [comment]
I don't think the issue is with the parameters already escaped, but some other part of the redirect URL returned from CashNet. It'd be good to get an example of the redirect URL encoding issue.

**Comment by ntalbott** [comment]
It does feel like the really brutal part is we don't have good data on the exact data that's failing. I wonder if the next step should be to roll back, but either here or in Spreedly, start capturing the failures for forensics.

**Comment by atuttle** [comment]
Apologies for butting in, but...

Isn't this the exact reason that methods like `canonicalize` (from OWASP's anti-sammy library) exist? My understanding is that canonicalize will un-encode everything to its raw form, and then you can then encode as appropriate for the request you need to make.

... not that this should excuse CashNet from sending bad data.

**Comment by sdball** [comment]
Awesome! I haven't used `canonicalize` before but it sounds like a potentially good approach. Like a less hacky version of the solution I proposed. :-)

**Comment by hoenth** [comment]
I agree with @ntalbott. We need to capture the times when it fails so we can be clear on the solution. Unfortunately, it means that for those times, we won't be notified about a completed transaction.
