### ISSUE TITLE
ActiveMerchant. SSL error in test mode

### ISSUE THREAD

**Issue by derk153** [activemerchant/active_merchant#2049]
I'm using ActiveMerchant gem for Paypal express checkout in my rails app.

I've deployed my project to production and I'm having an error message

> ActiveMerchant::ConnectionError (The SSL connection to the remote server could not be established)

I don't have this error in development and in production I'm still using test mode.

> config/initializers/active_merchant.rb

```
ActiveMerchant::Billing::Base.mode = :test
::EXPRESS_GATEWAY = ActiveMerchant::Billing::PaypalExpressGateway.new(
    login: CONFIG['PP_USER'],
    password: CONFIG['PP_PASSWORD'],
    signature: CONFIG['PP_SIGN']
)
```

How can I fix this error without installing SSL for test mode? Is it possible at all don't use SSL for Paypal Express Checkout?

**Comment by ntalbott** [comment]
This is almost always due to an old Ruby and/or OpenSSL - do your dev and prod Rubies & OpenSSL's match?

**Comment by masak2009** [comment]
I have same problem with PayPal:

Running active-merchant on my development machine without test mode:

Result of post to paypal: 

`#<Net::HTTPOK 200 OK readbody=true>`

Running active-merchant on my development machine with test mode:

`OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure`

I tried override active-merchant http method to force TLS

```
  def http
      http = Net::HTTP.new(endpoint.host, endpoint.port, proxy_address, proxy_port)
      configure_debugging(http)
      configure_timeouts(http)
      configure_ssl(http)
      configure_cert(http)
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      http.ssl_version = :TLSv1
      http
    end

```
Looks like that test mode still forcing SSL3 in post to paypal.

If test-mode not work but normal mode works then problem is not in OpenSSL !!!

Version of gem is "1.43.3" and Rails 3.2. The older one ("1.32.1") which works only with Rails 3.1 don't have this issue. I used the activemerchant in project for few years without problem. Now I can not make changes in project checkout to test paypal in test mode :-1:

**Comment by ntalbott** [comment]
The latest version of ActiveMerchant is 1.58.0 - can you please try with the latest and see if this is still happening?

**Comment by masak2009** [comment]
Project is on Ruby 1.9.3 and activemerchant 1.58.0 require Ruby version >= 2. 

Still not resolved.

**Comment by masak2009** [comment]
OK so I found where is problem:

Configuration: Still using version 1.43.3, Rails 3.2 and Ruby 1.9.3

My workaround to get it work:

1) Upgrade macports to be able install new ports on OSX El Capitan. (maybe unnecessary step => I have to do it because nokogiri native gem dependencies)

2) Upgrade rvm to latest version

3) Reinstall with force ruby 1.9.3 => You will see that ruby will be installed and then SSL3 ruby patch will be applied automatically.

```
rvm update head
rvm --force install 1.9.3

```
4) DONE => test mode works again!!!
