### ISSUE TITLE
VisaNet Peru exception

### ISSUE THREAD

**Issue by rwdaigle** [activemerchant/active_merchant#2058]
@shasum you're probably best positioned to look into this? Not sure under what circumstance the merchant id is not being returned?

```
#<TypeError: no implicit conversion of nil into String>

/srv/core/current/vendor/bundle/ruby/2.1.0/bundler/gems/active_merchant-fc32c3ca8d6a/lib/active_merchant/billing/gateways/visanet_peru.rb:155:in `+'
/srv/core/current/vendor/bundle/ruby/2.1.0/bundler/gems/active_merchant-fc32c3ca8d6a/lib/active_merchant/billing/gateways/visanet_peru.rb:155:in `url'
/srv/core/current/vendor/bundle/ruby/2.1.0/bundler/gems/active_merchant-fc32c3ca8d6a/lib/active_merchant/billing/gateways/visanet_peru.rb:127:in `commit'
/srv/core/current/vendor/bundle/ruby/2.1.0/bundler/gems/active_merchant-fc32c3ca8d6a/lib/active_merchant/billing/gateways/visanet_peru.rb:38:in `authorize'
/srv/core/current/vendor/bundle/ruby/2.1.0/bundler/gems/active_merchant-fc32c3ca8d6a/lib/active_merchant/billing/gateways/visanet_peru.rb:22:in `block (2 levels) in purchase'
/srv/core/current/vendor/bundle/ruby/2.1.0/bundler/gems/active_merchant-fc32c3ca8d6a/lib/active_merchant/billing/response.rb:59:in `process'
```

**Comment by shasum** [comment]
@rwdaigle 
seeing that it has originated from a purchase tx, I'd suspect merchant_id has not been passed in the options object. Like we did with purchase_number, maybe it's good to provide a default in our adapter, which would then cause an error response from the gateway that can be handed back to the user?

**Comment by rwdaigle** [comment]
What is the purpose of the merchant id from their docs? Is it assigned once per merchant account, or is it a value that can change with each transaction?

**Comment by shasum** [comment]
@rwdaigle 
assigned once per merchant account. I believe visanet assigns it to the merchant while setting up an account. It has been shared on our Trello api test credentials section and not generated by any of our invoked api calls.

**Comment by rwdaigle** [comment]
@shasum ah, ok then. I believe we should update this gateway to include `merchant_id` as a required credential that's passed to `initialize`.

And.. if we do that, we should be able to simplify the authorization format as well?

**Comment by shasum** [comment]
@rwdaigle 
good suggestion. yes, it simplifies auth format as well.

**Comment by duff** [comment]
I also noticed that our remote tests are passing lots of options:
https://github.com/activemerchant/active_merchant/blob/master/test/remote/gateways/remote_visanet_peru_test.rb#L13-L23

It may be useful to have a remote test that uses no options like this:

https://github.com/activemerchant/active_merchant/blob/master/test/remote/gateways/remote_creditcall_test.rb#L22

That `purchase_number` field looks :fish:y.

For things like that, we often give it a random string in the gateway:

https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/nab_transact.rb#L165

And sometimes we allow them to override it:

https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/fat_zebra.rb#L131


Looks like we're defaulting it:

https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/visanet_peru.rb#L91

I'm curious what `purchase_number` means.  Is that an `order_id`?  If so, we could use that as the override key.

**Comment by shasum** [comment]
@duff @rwdaigle 
Yes, quite a list of options. I took it as a collection point of all the required fields.
```
@options = {
  purchase_number: rand(100000000 .. 1000000000).to_s,  ( this is visanet's equivalent of order id, just needs to be 9-digit numeric. I thought it'd be good to retain their field name, hence included in options instead of order id. This field has default with override as already noted by @duff. If order id is the preferred standard, I can use that for override and get rid of this option )
  order_id: (SecureRandom.random_number() * (10 ** 9)).floor.to_s, ( redundant, not being used in the current version of the adapter )
  billing_address: address, ( a common options field )
  email: "visanetperutest@mailinator.com", ( required field, what's a good way to default it? )
  merchant_id: "101266802", ( this will be removed, this is going with the other credentials )
  device_fingerprint_id: "deadbeef", ( required field, now that I see the pattern, probably good to add a default with override )
  merchant_define_data: {
    field3: "movil",  # Channel ( required field, what's a good way to default it as it represents something about the merchant?  or should this go with the credentials just like merchant id)
    field91: "101266802", # Merchant Code / Merchant Id ( this will be removed, this is going with the other credentials )
    field92: "Cabify" # Merchant Name ( required field, what's a good way to default it as it represents something about the merchant?  or should this go with the credentials just like merchant id)
  }
}
```
The no-options test is definitely a good addition. I can do that if we settle on reasonable defaults for some of those other listed fields.

**Comment by rwdaigle** [comment]
@shasum 

If the gateway is requiring all those (meaningful) fields, we shouldn't create defaults. The caller will just have to provide them when they call AM.

Also, @duff has a good point about the order_id. We can set the purchase_number as the order_id, providing a default as you're already doing if no order_id is provided. If the caller passes in an alphanumeric order id, it will raise an error at the gateway (which is fine).

**Comment by duff** [comment]
I just noticed that it looks like for a whole bunch of gateways, we're stripping out bad characters from passed in `order_id`'s.  If you grep for "order_id.*gsub" you'll see a bunch.

**Comment by rwdaigle** [comment]
> we're stripping out bad characters from passed in order_id's

Ugh, that seems bad, no? Chances of collision are high - and changing data seems much worse than creating new data. Is that really a pattern we want to propagate?

**Comment by ntalbott** [comment]
@rwdaigle the issue we've seen is that ActiveMerchant users that operate across many different gateways use a common `order_id` that's relevant to their system, which doesn't necessarily conform to the requirements for a given gateway. If we don't clean it up for them, they have to know the requirements for each gateway they're dealing with.

**Comment by shasum** [comment]
@rwdaigle 

List of changes:
- remove `merchant_id` from options and make it a required credential passed to `initialize`
- simplify authorization format by stripping out `merchant_id` from it
- remove `purchase_number` from options, use `order_id` to override default `purchase_number`
- ?? no other changes to existing options ??
- clean up `order_id` ( little unclear on what guides this. example: visanet peru order_id needs to be 9-digit numeric, latitude19 has no specific restrictions except the field type is listed as a 100-char string. how would we clean it in these 2 situations? )

In case I missed anything, please feel free to include.

**Comment by rwdaigle** [comment]
@ntalbott 

> they have to know the requirements for each gateway they're dealing with

Yes.. they do :)

@shasum 

List of changes look good. Re:

> clean up order_id ( little unclear on what guides this. example: visanet peru order_id needs to be 9-digit numeric, latitude19 has no specific restrictions except the field type is listed as a 100-char string. how would we clean it in these 2 situations? )

We only clean up the order_id if the gateway imposes restrictions on its length and format. So for VisaNet here, we need to make it a numeric and truncate it to 9 digits. For Lat19, that's a flexible enough format that we probably don't need to do anything but pass along the order_id as it was given to us.

Hope that helps!

**Comment by shasum** [comment]
@rwdaigle 

> We only clean up the order_id if the gateway imposes restrictions on its length and format. So for VisaNet here, we need to make it a numeric and truncate it to 9 digits. For Lat19, that's a flexible enough format that we probably don't need to do anything but pass along the order_id as it was given to us.

visanet peru `order_id` from merchant What-ifs:
- less than 9-digits numeric - pad with leading zeros, provided gateway accepts it?
- greater than 9-digits numeric - truncate LSBs (or MSBs), won't this risk duplicates eventually?
- any-digits hex - not sure how to clean this up?

**Comment by rwdaigle** [comment]
> less than 9-digits numeric - pad with leading zeros, provided gateway accepts it?

It has to be exactly 9-digits?!? If so, then yeah, I guess pad it (but only if it has to be 9 digits)

> greater than 9-digits numeric - truncate LSBs (or MSBs), won't this risk duplicates eventually?

Yes, it will. But it seems that's the pattern to follow in AM...

> any-digits hex - not sure how to clean this up?

Any alpha character just remove it.

**Comment by shasum** [comment]
@rwdaigle 

Yes, their `order_id`( aka `purchase_number`) needs to be exactly 9-digits. Depending on the incoming `order_id` from the merchant, all this gsubbing may alter it beyond recognition.

Visanet Peru provides a piggy back field where we can set arbitrary key/value pairs that will make a round trip and be returned in the response. Why don't we use that to list both merchant generated `order_id` and our adapter generated `compliant_order_id`. That way we not only make sure a proper `order_id` gets forwarded to the gateway, but also the mapping is conveyed back to the merchant.

**Comment by rwdaigle** [comment]
@shasum what is the format requirement for `externalTransactionId`?

**Comment by shasum** [comment]
Good question. 4-things to consider.
- visanet uses a merchant supplied value (`purchase_number`) as it's tx id
- gateway does not return this `purchase_number` in any of the response fields
- current adapter does not rely on `order_id` to derive `purchase_number` (required to be 9-digit numeric)
- since it's not derived from `order_id`, it needs to be made available in generated authorization, for subsequent requests to id the right tx

`externalTransactionId ` is an open ended field defined by the merchant. Does not have a specific functional impact. Gets returned from request to response. In the current adapter version, it is being used to piggy back the `purchase_number` from request to response.

example: we send an `authorize` request with `externalTransactionId`==`purchase_number`. From the gateway response, we are able to look at `externalTransactionId ` to get the `purchase_number` and add it to the returned authorization. subsequent capture (or) void calls extract it from the authorization to refer to the right previous tx.

**Comment by rwdaigle** [comment]
@shasum does this make sense?

* Set the `externalTransactionId` to be the passed in `order_id`. It will remain unaltered and will be available in the response
* Set the `purchase_number` to be a randomly generated 9-digit number. Since this is an opaque identifier, it's fine if it's not returned in the response (that's the purpose of the external transaction id)

?

**Comment by shasum** [comment]
@rwdaigle 

prior `purchase_number` is needed in capture and void, it serves as the tx id in this gateway. either has to make a round trip or has to have a correlation between `purchase_number` and `order_id` such that earlier value can be re-computed.

**Comment by shasum** [comment]
@rwdaigle 

essentially dealing with two different necessities.
- `purchase_number` got to be different from `order_id`
- `purchase_number` needed back in the response

**Comment by rwdaigle** [comment]
@shasum could you pass in the generated purchaseNumber to the `commit` method as an argument so it can be added as the response authorization, when needed?

**Comment by shasum** [comment]
@rwdaigle 

nice, that should definitely work :+1: 

why oh why do we fail to see the simple elegant solution sometimes :)

**Comment by briannevillano** [comment]
@rwdaigle @duff @shasum let me know if this needs to be a new issue, or it it's related to the work done for this one:

They got a new error 400, this time 'Missing email':

=> #<Spreedly::Purchase:0x007fb842473360
@amount="400",
@created_at="2016-04-25T07:55:06Z",
@currency_code="PEN",
@description="Cabify payment",
@email="",
@gateway_specific_fields={},
@gateway_token="2FPShlkqSvYmxLMNsqHLrbyKWzN",
@gateway_transaction_id="",
@ip="81.44.165.26",
@merchant_location_descriptor="",
@merchant_name_descriptor="",
@message="[ \"Missing email\" ]",
@on_test_gateway="false",
@order_id="1617rt5VbUO5",
@payment_method=
#<Spreedly::CreditCard:0x007fb842443890
@address1="",
@address2="",
@card_type="visa",
@city="",
@company="",
@country="",
@created_at="2015-11-23T21:53:33Z",
@data="",
@eligible_for_card_updater="",
@email="",
@errors=[],
@fingerprint="0dcb729fa60a3155d41cbf1990a97b3a8c92",
@first_name="GERARDO",
@first_six_digits="455170",
@full_name="GERARDO REATEGUI",
@last_four_digits="2391",
@last_name="REATEGUI",
@month="11",
@number="XXXX-XXXX-XXXX-2391",
@phone_number="",
@state="",
@storage_state="retained",
@token="3puZPGyJmHNB5sxmcYtKFq1xwtd",
@updated_at="2016-04-02T06:24:08Z",
@verification_value="",
@year="2019",
@zip="">,
@response=
#<Spreedly::Response:0x007fb8424533d0
@avs_code="",
@avs_message="",
@cancelled="false",
@created_at="2016-04-25T07:55:06Z",
@cvv_code="",
@cvv_message="",
@error_code="400",
@error_detail="",
@fraud_review="",
@message="[ \"Missing email\" ]",
@pending="false",
@success="false",
@updated_at="2016-04-25T07:55:06Z">,
@shipping_address=
#<Spreedly::ShippingAddress:0x007fb842448e30
@address1="",
@address2="",
@city="",
@country="",
@name="GERARDO REATEGUI",
@phone_number="",
@state="",
@zip="">,
@state="gateway_processing_failed",
@succeeded="false",
@token="EiMKOj0DyUUkmVvls4ST2VpXYg8",
@updated_at="2016-04-25T07:55:06Z">

So I asked them to pass through an email to see what message/error they got:

The first time, it worked. He tried two more times: the first one he got a 400 error with no message, the second one he got "@message="Next Step not found for current step visanet.antifraud"

**Comment by shasum** [comment]
@briannevillano @duff @rwdaigle 

**email** is required

The inconsistent success and failure is definitely strange. Earlier, during development, came across a similar error signature,
> Next Step not found for current step merchant.query"

Their suggestion at that time was to re-check our `access_key_id` and `secret_access_key`. The keys were okay and we resolved the problem by making a change to the way Authentication header was formatted by switching to `Base64.strict_encode64`

Subsequent to passing email, was there any minor change in inputs between the time it succeeded and the times it failed. Could we try get the full transaction dump for both the success and fails. Could we also check if they used the same credentials during both success and failure?

Re-ran remote test suite, just to check, and it runs okay.
