### ISSUE TITLE
TLS v1.2 compatibility

### ISSUE THREAD

**Issue by brandoncc** [activemerchant/active_merchant#2060]
I'm sorry if this question has been answered somewhere already, I didn't find an answer though. I am working on an older Rails app, v2.3. We are using ActiveMerchant v1.4.1. We use authorize.net which has announced that they will be disabling TLS v1 and possibly TLS v1.1. I need to make sure that the app will work with TLS v1.2, but I am not sure where to start to test it. I'm not sure if that version if ActiveMerchant supports it. I would appreciate any help I can get on this. Thank you :smiley:

**Comment by girasquid** [comment]
Is this covered by the chat we had on the other issue?

**Comment by brandoncc** [comment]
Yep, I guess it is. I forgot about this one I had opened. I did open another one about RC4 cipher that I don't have any answer for yet though. Thanks for your help!

**Comment by ksolvesnutra** [comment]
@girasquid Can you please check #2812? I just want to confirm if we're using TLS v1.2 for BeanStream using activemerchant v 1.50.0.

**Comment by atul25khanduri** [comment]
@girasquid Can you please check #2812? I just want to confirm if we're using TLS 1.2 in activemerchant v1.50.0 in BeanStream Payment Gateway.
