### ISSUE TITLE
RC4 Cipher being disabled by Authorize.net

### ISSUE THREAD

**Issue by brandoncc** [activemerchant/active_merchant#2061]
I was notified that Authorize.net is disabling RC4, and that if we use a solution that needs it, we should update our solution. Are there any setting related to this in ActiveMerchant? I am not all that familiar with SSL, so I am not sure if this is only something the server op needs to worry about, or if I need to change anything in ActiveMerchant as well. Thanks.

**Comment by ntalbott** [comment]
So long as you're on a modern (2.1+) version of Ruby and recent version of OpenSSL, you should be fine. That said, your only real guarantee is to verify in your own environment.

**Comment by brandoncc** [comment]
@ntalbott  Ruby 1.8.7, Rails 2.3, OpenSSL 1.0.1e-fips 11 Feb 2013

I'm not in a position to upgrade anything like Ruby, I just do minor work on it. So there is nothing I need to change in ActiveMerchant or my app to make this work?

**Comment by ntalbott** [comment]
@brandoncc in that old of a Ruby version, I'd say there's a decent probability it will break unless proven otherwise. You'd need to test against an endpoint that looks like Authorize.Net will after the change, and see what happens. And a Ruby and/or OpenSSL upgrade may be required.
