### ISSUE TITLE
Add Adyen Gateway with their version 12 of the API

### ISSUE THREAD

**Issue by hallelujah** [activemerchant/active_merchant#2071]
Hello,

This gem had Adyen back ago but it was removed due to, as I understood, Adyen not making public their API. #1692 Or maybe am I wrong?

But now Adyen released a version 12 of their API.
Does it make sense to add Adyen gateway? If yes, anyone interested in working with me?

**Comment by hallelujah** [comment]
Hi, just pinging about this one.

We made our own implementation of Adyen Gateway https://github.com/3scale/active_merchant/tree/adyen

Please let us know if it is proper to a pull request or tell us what is required?

Regards

**Comment by orenmazor** [comment]
Hey 👍  interest in this. @davidsantoso @jasonwebster thoughts?

**Comment by davidsantoso** [comment]
@orenmazor I think it might be good to have someone from Adyen confirm that they are 👍 with being in Active Merchant. In the past they haven't been too keen on third party libraries.

**Comment by lyverovski** [comment]
Adyen is also currently on Version 18 of their spec. It's probably worth jumping straight to that version once they green light the addition.

**Comment by adyenpayments** [comment]
Hi All,

We have just pushed a PR for a new integration to the Adyen Platform using the latest version of our APIs. 

Regards,
Rik
Adyen

**Comment by jasonwebster** [comment]
See https://github.com/activemerchant/active_merchant/pull/2272 for the PR mentioned above. We'll use that to track the addition.
