### ISSUE TITLE
IATS ACH response error

### ISSUE THREAD

**Issue by timkleier** [activemerchant/active_merchant#2075]
When I try to store a token through the IATS Gateway for ACH, it gives me an "undefined method 'start_with?' for nil:NilClass" error. Looking at the response, it has a status of 'Failure' and error of "Object reference not set to an instance of an object." Any idea what's happening? My code is below.

```
# Active Merchant 1.58.0, Ruby 2.2.2, ActiveSupport 4.2.1, Nokigiri 1.6.7.2

check = ActiveMerchant::Billing::Check.new(
      :first_name         => 'Test',
      :last_name          => 'Person',
      :routing_number     => '111111111',
      :account_number     => '12345678',
      :account_type       => "checking")

iats_gateway_users = ActiveMerchant::Billing::IatsPaymentsGateway.new(
  :login => 'TEST88',
  :password => 'TEST88')

iats_gateway_users.store(check, options={ :billing_address => { :address => "1234 Any Street", :city => "Fort Collins", :state => 'CO', :zip_code => '80524' }})





```

**Comment by bpollack** [comment]
Are you still seeing this @timkleier ?

**Comment by timkleier** [comment]
I'm not sure, it was awhile ago that I worked on this project. I'd say you can close this unless others are experiencing the same issue.

**Comment by bpollack** [comment]
Got it. I haven't heard of this, but I'll keep an ear out. For now, I'll close it. Thanks @timkleier !
