### ISSUE TITLE
Partial Refund customer code issue

### ISSUE THREAD

**Issue by fastspud** [activemerchant/active_merchant#2078]
Recently we have been having problems settling our transaction automatically at the end of the day in Converge due to certain partial refund transaction having a customer code populated with the first 10 characters of their email address.  When this happens the transaction cannot be settled because it is an incorrect customer code for the card provided.  This seems to only be happening when there is no sales tax being refunded.

Can you see any reason why this is happening?  I feel like it is a Shopify issue, like they are useing
credit(money, creditcard, options = {})
incorrectly.

Any help on this issue would be great.

**Comment by ntalbott** [comment]
@fastspud if you're using Shopify, you should take this issue up with them. It's out of scope for the ActiveMerchant maintainers. Thanks!
