### ISSUE TITLE
Stripe metadata and customer info not set for EMV

### ISSUE THREAD

**Issue by Amos47** [activemerchant/active_merchant#2080]
### Stripe metadata and customer info not set for EMV

We are not setting metadata and customer information for EMV transactions with Stripe.

I expect it's because in the early versions of the API this wasn't allowed to be set, but it's incredibly useful for debugging and reconciliation.

Problem Code:
https://github.com/activemerchant/active_merchant/blob/b1c5c11812a2284a2a9c566e5efd34064006040b/lib/active_merchant/billing/gateways/stripe.rb#L278-L287

/tag @bizla

**Comment by bizla** [comment]
Closing this as https://github.com/Shopify/shopify/issues/76739 tracks the actual AM bump.
