### ISSUE TITLE
Pass application_id in as an option

### ISSUE THREAD

**Issue by luukveenis** [activemerchant/active_merchant#2088]
Gateways have a class attribute called [application_id](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateway.rb#L134-L135). In the case of the BraintreeBlue gateway it is used to associate payments with libraries. We have had a request to set this value from Braintree but are concerned about setting this for every instance of the gateway. Ideally, it seems like we'd be able to pass this in as an option along with the rest of the request data, or change this to an `attr_accessible` on the instance itself rather than setting it on the class. Does anyone see any problem with trying to do this for BraintreeBlue and other gateways that behave similarly?

**Comment by davidsantoso** [comment]
Hi @luukveenis- looks like in Braintree Blue we currently [pass it as the `channel` option](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/braintree_blue.rb#L603). I believe this should allow you to pass it for only Braintree transactions vs setting it for all gateways.
