### ISSUE TITLE
adding payment gateway to shopify

### ISSUE THREAD

**Issue by ygokirmak** [activemerchant/active_merchant#2101]
Hi all..

I couldn't find any mail group or alternative way to ask this question, sorry for messing..

Assume I developed my gateway's implementation for active_merchant like all other gateways,
So what is the procedure to add new gateway to shopify gateway list as below

There should be some way to implement this simple view for my gateway because as I see all gateways has different requirements and their forms are differs . For example airpay asks for HMAC key while another gateway asks for password..

Should I develop some shopify app after active_merchant implementation?

![screenshot-ygok myshopify com 2016-05-12 08-55-37](https://cloud.githubusercontent.com/assets/848191/15205513/aad86330-1820-11e6-9794-e282e459b62d.png)

**Comment by ntalbott** [comment]
@ygokirmak you should get in touch with Shopify directly, as many of us don't work there and Shopify support isn't done here. Thanks!
