### ISSUE TITLE
secure profile payments beanstream

### ISSUE THREAD

**Issue by awladnas** [activemerchant/active_merchant#2102]
**I think It will be a query than an issue.**

I am using profile API.  After digging source code I found I need to pass `secure_profile_api_key` during gateway initialization. I can create customer profile by store.

I think we can purchase using customer code. When I was calling purchase  I got `Declined - Entered Information Cannot Be Authenticated`. 
I was passing a string customer code that I got as the response of the store. I checked store is creating customer profile successfully.  I was trying like this: `gateway.purchase(200, 'CUSTOMER_CODE')`

I tried with `beanstream` gem. Purchasing is working with the same customer code. In this case I had to pass `payments_api_key`. It seems that there is no option for `payments_api_key` in the activeadmin. 

How can I process purchase/capture/authorize with customer code?

Here is response I got after calling purchase:
`<ActiveMerchant::Billing::Response:0x000000037eee58 @params={"trnApproved"=>"0", "trnId"=>"0", "messageId"=>"804", "messageText"=>"Declined - Entered Information Cannot Be Authenticated", "trnOrderNumber"=>nil, "authCode"=>nil, "errorType"=>"N", "errorFields"=>nil, "responseType"=>"T", "trnAmount"=>nil, "trnDate"=>"5/12/2016 1:25:25 PM", "avsProcessed"=>"0", "avsId"=>"0", "avsResult"=>"0", "avsAddrMatch"=>"0", "avsPostalMatch"=>"0", "avsMessage"=>"Address Verification not performed for this transaction.", "cardType"=>nil, "trnType"=>"P", "paymentMethod"=>nil, "ref1"=>nil, "ref2"=>nil, "ref3"=>nil, "ref4"=>nil, "ref5"=>nil, "hashValue"=>"9ad61d245ff5de08d3a9855c992ab9cc07d89427"}, @message="Declined - Entered Information Cannot Be Authenticated", @success=false, @test=true, @authorization="0;;P", @fraud_review=nil, @avs_result={"code"=>"R", "message"=>"System unavailable.", "street_match"=>nil, "postal_match"=>nil}, @cvv_result={"code"=>nil, "message"=>nil}>
`

**Comment by ntalbott** [comment]
@awladnas you'll want to look at the ActiveMerchant code to see how it's interacting with the Beanstream API; if you find a bug, please do file an Issue and we'll try to fix it. Thanks!

**Comment by awladnas** [comment]
@ntalbott 
Thanks for your reply.I can not find any example of purchasing from customer profile of beanstream gateway. Can you provide one?
I  was not able to `set payments_api_key`. Can you help how can I set it ?
There is only one example of purchasing, there is no example for storing and purchasing with secure payment.

**Comment by ntalbott** [comment]
@awladnas nope, can't help with those things. Gateway-specific support is really down to reading the code and poking at the API.

**Comment by alexdunae** [comment]
@awladnas here's how it works for me:

```ruby

gateway = ActiveMerchant::Billing::BeanstreamGateway.new(
  login: 'XX',
  user: 'XX',
  password: 'XX',
  secure_profile_api_key: 'XX' # This is from Beanstream's Profiles section
)

response = gateway.store(credit_card, params)
customer_id = response.params['customerCode']

# charge card via customer profile
payment = gateway.purchase(25_00, customer_id)
assert payment.success?
```
