### ISSUE TITLE
Getting error in braintree gateway for migrate to Orange Platform to Blue Platform.

### ISSUE THREAD

**Issue by shantilal-narola** [activemerchant/active_merchant#2144]
I have used active_merchant plugin in rails 2 application.In last few days(Till 3rd June) It will give me error. something like this **User 'nextproof' is not allowed to process electronic check credit transactions. REFID:3184245349** due to migrate the orange Platform to Blue Platform. So please help to resolve this error.

**Comment by ntalbott** [comment]
That's a Braintree error, you'll need to take it up with them.

**Comment by shantilal-narola** [comment]
Thank you @ntalbott , Braintree Support Team was solved this error.
