### ISSUE TITLE
PayPal Express Refunds - no fee information provided

### ISSUE THREAD

**Issue by lucovico** [activemerchant/active_merchant#2181]
Response from PayPal does not contain any information on fees refunded. It only contains the gross_amount of the refund. I'm using:

`gateway.transaction_details("REFUND_TRANSACTION_ID")`

Maybe this is not the right way to do it? Any help would be appreciated.

**Comment by bpollack** [comment]
We're unfortunately not using PayPal Express internally, so I'm not sure I can provide a lot of help. If you want, please feel free to submit a PR that corrects the issue you're hitting when you figure it out.
