### ISSUE TITLE
New Payment Support

### ISSUE THREAD

**Issue by arjunmenon** [activemerchant/active_merchant#2199]
Hi.
Please add support for [Razorpay](https://razorpay.com/) as well.

https://docs.razorpay.com/

**Comment by davidsantoso** [comment]
Hi @arjunmenon you're welcome add this gateway if you're wanting/needing to use it. However Active Merchant maintainers will not be adding it. See our [contributing wiki page](https://github.com/activemerchant/active_merchant/wiki/Contributing) for more details.

**Comment by MID4D881527** [comment]
#01011030370502#payment support

**Comment by MID4D881527** [comment]
Account self me
