### ISSUE TITLE
Payment support for one of the biggest Russian platforms PayAnyWay

### ISSUE THREAD

**Issue by shaded13** [activemerchant/active_merchant#2204]
Hello! Is it possible to add as a inner payment option PayAnyWay (Moneta).https://payanyway.ru/info/w/en/public/w/partnership/developers/cms.html
There are a lot of CMS modules supported but not Shopify.
https://payanyway.ru/info/w/en/public/w/partnership/developers/cms.html
Thank you so much!

**Comment by ashukasama** [comment]
@shaded13 , we can help you to create this payment gateway in Shopify as an alternative payment option.

**Comment by bpollack** [comment]
We aren't currently accepting requests for new gateways through Active Merchant, so I'm going to close this out at this point.
