### ISSUE TITLE
Flow.io Gateway Implementation

### ISSUE THREAD

**Issue by Tonkpils** [activemerchant/active_merchant#2224]
I am implementing a PR for the https://flow.io payment gateway and I was wondering...the Wiki mentions.

> No new gem dependencies 

Flow provides a Ruby SDK for their API endpoints which I'm using as part of the implementation and I followed Braintree's gateway as a guide and added Flow's SDK to the `Gemfile` which would ensure that if anyone wants to use the Flow.io gateway would need to add the SDK to their own Gemfile.

Is the restriction for new gem dependencies at the `gemspec` level or does it also include `Gemfile` dependencies?

Thanks

**Comment by jasonwebster** [comment]
> Is the restriction for new gem dependencies at the gemspec level or does it also include Gemfile dependencies?

Only the gemspec level. That guideline is there to avoid requiring everyone that uses Active Merchant to install some gem they'll never use. It's perfectly ok to use SDKs in gateways as long as they're required just in time. Take a look at the [Braintree implementation](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/braintree_blue.rb#L3-L7) for an example.

**Comment by bpollack** [comment]
ThIs seems resolved at this point, so I’m closing. Please feel free to reopen if I’ve misunderstood.
