### ISSUE TITLE
Authorize.net - allow settings for CIM purchases

### ISSUE THREAD

**Issue by fwilkens** [activemerchant/active_merchant#2237]
Currently you can specify settings for non-cim purchases: https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/authorize_net.rb#L216

I'm proposing to add the same for CIM purchases: https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/authorize_net.rb#L221

This would allow setting things like the duplicate window, recurring billing, etc.

**Comment by mward-nerdery** [comment]
:+1: for this. Our team would certainly take advantage of being able to set the duration window

**Comment by bpollack** [comment]
This was implemented in b4de7a7b6892db2a605890fbeebea186e76d0657
