### ISSUE TITLE
OrbitalGateway#capture does not recognize order_id parameter

### ISSUE THREAD

**Issue by yaychris** [activemerchant/active_merchant#2247]
I'm going through the Orbital certification process and my "capture" test cases were rejected because I did not provide the `OrderID`.

In trying to do so, I discovered that ActiveMerchant [does not allow the `order_id` parameter for capture transactions](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/orbital.rb#L589). By comparison, void transactions [do allow it](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/orbital.rb#L607).

**ActiveMerchant**: 1.60.0
**Ruby**: 2.3.1
**ActiveSupport**: 5.0.0.1
**Nokogiri**: 1.6.8.1

**Comment by bpollack** [comment]
Looks to me as if this was resolved in #2248, so closing, but please reopen if I’ve misunderstood.
