### ISSUE TITLE
Create new standard error code for declines due to no network tokenization support

### ISSUE THREAD

**Issue by jasonwebster** [activemerchant/active_merchant#2269]
The world isn't going to be running PANs over the internet forever. Apple Pay, Android Pay, etc. all rely on gateways and processors supporting network tokenization (and each major network has their own way of doing this). While Active Merchant supports processing these payment tokens, it does not provide any standardized abstraction for when processing them fails due to lack of gateway/processor support.

**Comment by bpollack** [comment]
Looks to me as if you handled this in 30028b69602891b0cece80ca6ea18a7dab78639d, so closing.
