### ISSUE TITLE
Litle does not send expiration date with token

### ISSUE THREAD

**Issue by wsmoak** [activemerchant/active_merchant#2273]
According to the Litle / Vantiv docs, we are supposed to be sending the expiration date when making purchases using a token.

http://litleco.github.io/faqs/#tokenization

> **Does the expiration date need to be sent with a token?**
> The expiration date must be sent in with a token. We only tokenize the card number. The token does not include the expiration date or card validation number. When the card expires you can simply send in the new expiration date without replacing the token.

(I'm working on a PR for this.)

**Comment by bpollack** [comment]
It _seems_ to me as if this is actually supposed to be closed, so I'm re-closing, but please feel free to re-open if I'm missing something.

**Comment by wsmoak** [comment]
I agree.  I fixed it in our fork and never got around to opening a PR here, but #2354 added the expiration date along with a couple of other things, so this issue is solved.
