### ISSUE TITLE
Checkout.com: invalid money_format (defined as decimals instead of dollars or cents).

### ISSUE THREAD

**Issue by RobertChanphakeo** [activemerchant/active_merchant#2276]
Refer to https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/checkout.rb

`      self.money_format = :decimals`

money_format can either be "dollars" or "cents" however "checkout.rb" moneyformat is decimals. According to checkout.com documentation the money format should be defined as "cents" (http://developers.checkout.com/docs/server/api-reference/charges)

**Comment by jasonwebster** [comment]
Hey! Thanks for the issue. Feel like submitting a quick PR to fix the issue?

**Comment by aemonm** [comment]
I dropped in a PR for this, #2344.

**Comment by bdewater** [comment]
PR merged 😄
