### ISSUE TITLE
Braintree gateway does not support adding cc to customer during transaction.

### ISSUE THREAD

**Issue by jgoodall628** [activemerchant/active_merchant#2283]
Currently, there is no way using the Braintree gateway to have a new credit card be stored in the vault for an existing customer, simultaneously with creating a transaction. Per the Braintree documentation:

To associate this transaction's payment method with an existing customer, pass a customer_id:

`result = Braintree::Transaction.sale(
  :amount => "10.00",
  :payment_method_nonce => nonce_from_the_client,
  :customer_id => "the_customer_id"
)`

As far as I can tell, there is nothing in the options parameter that I can pass that will allow me to have the credit card saved on the customer while also proceeding with the transaction.

**Comment by bl** [comment]
It sounds like you're describing two separated actions to store the new credit card, then create a transaction. From my knowledge both these actions are defined and implemented separately on the Braintree's `store` and `purchase` actions.

Is there a particular reason why you're looking to perform both of these simultaneously?

**Comment by bpollack** [comment]
I think I agree with @bl here; I'm going to close this issue for now. Please feel free to reopen if you've got more information.
