### ISSUE TITLE
Drop Ruby 2.0 support

### ISSUE THREAD

**Issue by jasonwebster** [activemerchant/active_merchant#2297]
2.0 was officially EOL'd February 24th, 2016. I'm exceptionally wary of supporting Active Merchant on versions of the language that are not officially supported anymore. 

The release of Nokogiri 1.7.0, which dropped support for Ruby =< 2.0 last week has kind of forced this issue for us, since our gemspec only specifies a minimum required version. Working around it on the gem dependency level is possible, but something that I'd like to avoid.

/cc @davidsantoso @rwdaigle

**Comment by rwdaigle** [comment]
I think it makes sense not to support old versions of Ruby, especially considering the sensitive data a library like AM deals with 👍

**Comment by davidsantoso** [comment]
Sounds reasonable to me!

**Comment by davidsantoso** [comment]
Closed with #2298
