### ISSUE TITLE
Bitpay?

### ISSUE THREAD

**Issue by reneklacan** [activemerchant/active_merchant#2316]
I noticed you previously supported Bitpay and it seems it was silently dropped. I couldn't find any information about it in changelog.

Was there any reason to drop it?

**Comment by bdewater** [comment]
It has been split off into a separate gem: https://github.com/activemerchant/offsite_payments/blob/master/lib/offsite_payments/integrations/bit_pay.rb

**Comment by reneklacan** [comment]
@bdewater I missed that. Thank you!
