### ISSUE TITLE
LiqPay (Ukraine)

### ISSUE THREAD

**Issue by xokvictor** [activemerchant/active_merchant#2321]
Hello guys! I want use LiqPay (https://www.liqpay.com/) best ukrainian gateway. Can you tell me please how I can integrate this gateway with my Shopify store?

**Comment by lsamayoa** [comment]
You would need to implement an adapter for that gateway, I see they have an API. I would be glad to help you if you can provide me with an account to that provider since I have no access to it from my country.

**Comment by xokvictor** [comment]
@lsamayoa thanks! Can you give me please your email, then I will send you access to the account of this provider.

**Comment by lsamayoa** [comment]
@xokvictor leonel01017@gmail.com

**Comment by trademinister** [comment]
Hello!
Did You get solution for LiqPay and Shopify?
