### ISSUE TITLE
The transaction currency specified must be the same as previously specified.

### ISSUE THREAD

**Issue by Ashviniv** [activemerchant/active_merchant#2346]
I am trying to integrate paypal express checkout on my website with the currency SGD. But it is giving a failure message as **The transaction currency specified must be the same as previously specified.**

I have tried by setting up SGD as primary currency in my paypal sandbox account. But still it gives the same failure message.It will be a great help, if anyone have solution for the issue?

**Comment by matthewheath** [comment]
Would you be able to provide a copy of your PayPal Express Checkout code here? It sounds like a currency was perhaps set in the `setup_purchase` method that doesn't match the transaction currency passed to the `purchase` method?

**Comment by bpollack** [comment]
There’s been no response for nine months, so closing out. Please feel free to reopen with more information.
