### ISSUE TITLE
Respecting http_proxy environment variable

### ISSUE THREAD

**Issue by techbelly** [activemerchant/active_merchant#2372]
Net::Http respects http_proxy environment variables:

https://ruby-doc.org/stdlib-2.4.0/libdoc/net/http/rdoc/Net/HTTP.html#method-c-new

"If none of the p_ arguments are given, the proxy host and port are taken from the http_proxy environment variable (or its uppercase equivalent) if present. If the proxy requires authentication you must supply it by hand. See URI::Generic#find_proxy for details of proxy detection from the environment. To disable proxy detection set p_addr to nil."

Because ActiveMerchant always gives p_ arguments to the constructor of Net:Http, this behaviour is, I think, unintentionally circumvented.

See pull request: #2371 for a potential fix.

**Comment by georgiev** [comment]
Please reopen - the issue is still a valid one in both - the master and the v1.95.0 tag. See PR #3244 for description.
