### ISSUE TITLE
Travis failure due to ActiveSupport version

### ISSUE THREAD

**Issue by shasum** [activemerchant/active_merchant#2373]
ref: #2370 #2371 

Seems a recent bump in Travis from `rails 5.1.0.beta1` to `rails 5.2.0.alpha` is causing a bundler error as it tries to resolve the ActiveSupport version.

- [activemerchant.gemspec](https://github.com/activemerchant/active_merchant/blob/master/activemerchant.gemspec#L24) restricts ActiveSupport to `< 5.1`
- Default for rails52 is `activesupport (= 5.2.0.alpha)`

We could either anchor [Travis](https://github.com/activemerchant/active_merchant/blob/master/.travis.yml#L16) to `5.1` or bump up [activemerchant.gemspec's](https://github.com/activemerchant/active_merchant/blob/master/activemerchant.gemspec#L24) version to `< 5.2`. The latter approach runs the risk of failing again when rails5 version moves up in Travis.

**Comment by davidsantoso** [comment]
@shasum thanks for looking into this! Looks like we've already got a pattern going for Rails versions lower than 5. Seems like this could be a good time to rename the `Gemfile.rails5` to `Gemfile.rails51` and then locking the Rails version in that particular Gemfile. Also, we'll need to update that reference in the `.travis.yml` file.

**Comment by davidsantoso** [comment]
@shasum thanks again for the debugging! Fixed with https://github.com/activemerchant/active_merchant/pull/2374.
