### ISSUE TITLE
Should we depend of ActiveSupport lib?

### ISSUE THREAD

**Issue by bricesanchez** [activemerchant/active_merchant#2417]
Hi all! 

Thanks for your awesome work on ActiveMerchant!

I'm currently investigating Hanami framework and i found this: https://github.com/davydovanton/stop_active_support_anywhere

Do you think it could be a great thing to not depend of ActiveSupport in this library?

:)

**Comment by bpollack** [comment]
Perhaps, but we're not likely to make this change anytime soon; the main consumers of this all use Rails, so removing ActiveSupport isn't something we're likely to prioritize. That said, PRs are always welcome.
