### ISSUE TITLE
Can I use 'Integaration' to integrate CCAvenue with ActiveMerchant

### ISSUE THREAD

**Issue by abhiramm** [activemerchant/active_merchant#2430]
I want to integrate CCAvenue with Active Merchant. As I can see there are two guidelines mentioned in this contributing [guide](https://github.com/activemerchant/active_merchant/wiki/GatewaysVsIntegrations) as Gateway and Integration, I think I can use only Integration method as ccavenue is a offsite payment gateway. But I don't know whether ActiveMerchant still supports Integration and also I couldn't find any detailed documentation regarding Integration. So my question is,

1. What are the guidelines I should follow to make CCAvenue work with activemerchant?
2. Should I use offsite payment gateway gem, but I want to integrate ccavenue with activemerchant as we are already using activemerchant in our application. so I want to integrate with activemerchant. can anyone guide me on this?

It will be very much useful if anyone guide me in the right direction.

**Comment by abhiramm** [comment]
Hi @ntalbott Can you help me on this. I got stuck here.

**Comment by bdewater** [comment]
The docs on this are a bit out of date. A gateway would exist in this repository, an integration would live in offsite_payments. The split happened in June 2014. 

Which one of the two to go with depends on the API. Some payment gateways support both options, and the choice would depend on the application requirements, the biggest one being PCI compliance for ActiveMerchant gateways.

**Comment by bdewater** [comment]
Closing this, please reopen if there's still something unclear.
