### ISSUE TITLE
Can I add offsite payment gateway like ccavenue with ActiveMerchant instead of adding it with offsite_payments gem

### ISSUE THREAD

**Issue by abhiramm** [activemerchant/active_merchant#2435]
Iam already using ActiveMerchant gem, now i want to include CCAvenue with Activemerchant but I can see that offsite payment gateways should be included in offsite_payments gem instead of ActiveMerchant. 

But i want to include ccavenue with Active Merchant can it be done? Will it be added with Active Merchant while submit if i integrate ccavenue with Active Merchant itself? 

It will be verym umch helpful if this is answered , as am stuck with this question. Thanks.

**Comment by bdewater** [comment]
The short answer is no, as explained in https://github.com/activemerchant/active_merchant/issues/2430#issuecomment-307126223

I'll close this issue so we can have the discussion in one place over there, if you have further questions.
