### ISSUE TITLE
VISANET PERU supported?

### ISSUE THREAD

**Issue by ignaciosm** [activemerchant/active_merchant#2437]
Hi,

I have a question, in the "Issues" section I see sevaral people mentioning issues (and fixing) with VISANET PERU, yet, I it doesn't show under the Supported Payment Gateways in the README.md?

Is it supported? Maybe it was at some point but not anymore? Or hopefully it is supported and just wasn't added to the list.

Thanks! Also, would this gem work with a Spree or Solidus store?

Thanks again

**Comment by bdewater** [comment]
That list is not up to date. When in doubt, use the source https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/visanet_peru.rb 😄 

Spree and Solidus specifcy activemerchant as a dependancy, so I expect it to work.

**Comment by ignaciosm** [comment]
great, thanks!

**Comment by bdewater** [comment]
You're welcome!
