### ISSUE TITLE
[PayU latam] Taxes are not being sent to PayU

### ISSUE THREAD

**Issue by lasg125** [activemerchant/active_merchant#2441]
I am having issues because Shopify is sending the total amount without breaking the base amount and the tax amount when the product has one, but if the product does not have they are not sending taxAmount = 0, so PayU is applying taxes for all my transactions, for example:

1 product $80.000 with taxes 19% (15.200) total amount = $85200, Shopify send the total amount without telling what is the tax and what the base amount. So PayU takes the $85200 and applies again a 19% so it its a bigger tax (16.188).

1 producto $140.000 without taxes, total amount  = $140.000 Shopify send the total amount without telling that the tax is 0. so PayU applies a tax 19% 26.600.

This happens  because of the nature of my account with PayU that  applies to every transaction the default tax of my country if i do not send the exact value of the tax even if it is 0.

i hope that someone could help me.

**Comment by bdewater** [comment]
Somebody's working on this 🎉  https://github.com/activemerchant/active_merchant/pull/2528

**Comment by jasonwebster** [comment]
Hi, just a kindly reminder that this isn't a support forum for Shopify. Active Merchant is an independent open source project used and maintained by many. 

As for your report, it looks like the PR that @bdewater linked above has been merged, and that's about all we can do here. I encourage you to reach out to Shopify's support team if you have any issues specifically with Shopify.
