### ISSUE TITLE
Is active merchant still a valid way to become an approved payments gateway for Shopify?

### ISSUE THREAD

**Issue by yjkimjunior** [activemerchant/active_merchant#2463]
is it? https://help.shopify.com/manual/payments/third-party-providers

**Comment by bdewater** [comment]
Shopify still uses ActiveMerchant but like the link states we're not using it to accept new payment providers on to our platform.

**Comment by bdewater** [comment]
I assume this answered the question, if not feel free to re-open the issue :)
