### ISSUE TITLE
Upgrade WePay API to 2017-05-31

### ISSUE THREAD

**Issue by OldSneerJaw** [activemerchant/active_merchant#2493]
The library currently targets an outdated version of the WePay API (2017-02-01) by default. Upgrade to the most recent version: 2017-05-31.

See the [WePay API Versions](https://developer.wepay.com/docs/versions) page for more info.

**Comment by bpollack** [comment]
As noted in #2494, this is part of how WePay works, and we can’t change the baseline without breaking downstream clients. You can override the version with the options hash or the WePay dashboard.
