### ISSUE TITLE
Vantiv (Litle) Url Update deadline approaching Aug 31 2017

### ISSUE THREAD

**Issue by kjbkjb** [activemerchant/active_merchant#2502]
My corporation does not allow me to contribute so I'm submitting an issue here:

Vantiv purchase Litle quite a while ago, now they are migrating their endpoints to their own domain with a hard deadline of 8/31
https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/litle.rb#L9

The live URL will be changing to https://payments.vantivcnp.com/vap/c
ommunicator/online
The test URL, as far as I can tell will not be changing.

We've monkey-patched for this change but perhaps someone in the contributor list can make this update to AM.

Contact me and I can provide Vantiv's FAQ on the topic.

**Comment by VantivSDK** [comment]
Hi @kjbkjb,
Vantiv can take this issue and submit a pull request with updated URLs. The test URL will change as well, we will update that too when all is ready to go live.

**Comment by kjbkjb** [comment]
THANK YOU!

**Comment by brianarnold789** [comment]
@kjbkjb pull request for prod and cert/prelive URL updates: https://github.com/activemerchant/active_merchant/pull/2504

**Comment by bruno** [comment]
Note this has already been done in #2531
