### ISSUE TITLE
[STRIPE] statement_descriptor vs. statement_description ?

### ISSUE THREAD

**Issue by hendie** [activemerchant/active_merchant#2512]
We are busy writing another gateway that also uses a statement_descriptor. My question is whether there is a typo in stripe.rb:310
```ruby
   post[:statement_descriptor] = options[:statement_description]
```
One would think that the option should be the same name as the param needed for the post? This option is not currently used by any other gateway, so I am just asking (maybe my OCD kicking in).

**Comment by jasonwebster** [comment]
Well, Active Merchant is ideally some layer of abstraction, right? We have some standardized and [documented options](https://github.com/activemerchant/active_merchant/wiki/Patterns-&-Standards#options) that all gateways should adhere to. What do you think the most correct option name would be, knowing that each gateway may call it something completely different on their API?

**Comment by hendie** [comment]
I understand about the abstraction, and in this case would go with what the services prefer to call it. They are closer to the FIs, and probably have a better handle on what things are called in the financial world. After a quick Google search, it looks like **descriptor** would be better than **description**. Some call it billing descriptor, transaction descriptor. So `statement_descriptor` seems to me like a good choice?

**Comment by bpollack** [comment]
Right now, Stripe is the only gateway that supports _either_ `statement_descriptor` or `statement_description`, but our general rule is that existing options are the standardized ones. Thus, I'd go with `statement_description`, since it's what Stripe expects in the `options` hash.

**Comment by bpollack** [comment]
(Alternatively, if you wanted to patch Stripe to handle both and your new gateway to handle just `statement_descriptor`, we could chat about that. The only other thing in the code base that comes close is Mercado Pago, which uses `statement_description` _in the response_.)
