### ISSUE TITLE
raw_json not recorded on payhub response

### ISSUE THREAD

**Issue by cimtico** [activemerchant/active_merchant#2516]
The line https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/pay_hub.rb#L204

where the raw_response would be added to the response should use double quotes for the interpolation to work. It is currently not interpolating and shows ` returned by the API was \#{raw_response.inspect}`

**Comment by bpollack** [comment]
This seems to have been fixed by #2572; closing.
