### ISSUE TITLE
Unable to make PayuInGateway work

### ISSUE THREAD

**Issue by Lorel** [activemerchant/active_merchant#2526]
Hi there,

I'm trying for few hours already to make [ActiveMerchant::Billing::PayuInGateway](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/payu_in.rb), but without any success

It looks like the "seamlessly" integration of PayU India returns a 302 with an HTML response where you can find the message "This process might take some time. Please do not hit refresh or back button or close this window.", and the gateway is not able to handle it

Here are the data sent:
```
amount=10.00&txnid=XoRXcwhBrYJnfTsUeg&productinfo=Purchase&surl=http%3A%2F%2Fexample.com&furl=http%3A%2F%2Fexample.com&pg=CC&firstname=Bob&lastname=Bobsen&bankcode=MAST&ccnum=5123456789012346&ccvv=123&ccname=Bob+Bobsen&ccexpmon=05&ccexpyr=2020&email=unknown%40example.com&phone=11111111111&key=gtKFFx&txn_s2s_flow=1&hash=41d2fec4f147b02a0b9ba5d7cccd324676e1e1c70ffc437a049f684f22d08d46f48f85e8c953ac33189bde8f4b82032abaab90067615f83bb5fb4a195365b1a9
```

Maybe it is not usable anymore with the current version of PayU's service?

Any idea anyone? cc @ntalbott @curiousepic

**Comment by ntalbott** [comment]
@Lorel Spreedly is still doing transactions on this gateway via ActiveMerchant, so it does work. However, as per our docs, it requires some settings changes on the PayU side to support it: https://docs.spreedly.com/payment-gateways/payu-in/. It says "to work with Spreedly" in our docs, but in reality the changes are required to work with ActiveMerchant in general. So you'd need to reach out to PayU India and ask them to make those tweaks to your account.

**Comment by Lorel** [comment]
@ntalbott thanks so much for your quick reply, highly valuable, you rock ;)
