### ISSUE TITLE
Getting bank_resp_code as "095" i.e. "Transaction not approved" for amount "5095.53" only.

### ISSUE THREAD

**Issue by SunnyKukkarFluke** [activemerchant/active_merchant#2610]
Hi team,

I am getting bank_resp_code as "095" i.e. "Transaction not approved" from API "gateway.purchase".
Please note that this response I am getting only for transaction amount "5095.53" i.e. for a particular products combination and for all other transactions (products) its working fine.

Below are some key values which I got in response. Please let me know in case u need any other info regarding this.

 "exact_message": "Transaction Normal",
  "bank_resp_code": "095",
  "bank_message": "Transaction not approved",
  "bank_resp_code_2": "",
  "transaction_type": "00",
  "dollar_amount": "5095.53",

Thanks,

Sunny

**Comment by bdewater** [comment]
Which gateway are you using? And have you contacted their support? This does not seem to be an issue with the code here since you're not getting an error, but a failure. There's a ton of reasons why an authorization might fail.

**Comment by bpollack** [comment]
Closing due to lack of additional information, but please feel free to reopen with more info.
