### ISSUE TITLE
Barclays EPDQ Extra Plus Gateway Certificate Validation

### ISSUE THREAD

**Issue by pacso** [activemerchant/active_merchant#2613]
As of 9th October 2017, Barclays EPDQ Extra Plus gateway has moved from a Symantec SSL certificate to using an Entrust SSL certificate.

The certificate in use is signed by the Entrust G2 and L1M keys, and as such the public keys for these must be available to validate the SSL certificate when connecting to `https://payments.epdq.co.uk/`.

Since these keys are not available in `active_merchant/lib/certs/cacert.pem`, SSL verification currently fails when attempting to process payments.

A solution to this issue is to add the G2 and L1M keys to the `cacert.pem` file.

**Comment by bpollack** [comment]
Merging into #2901.
