### ISSUE TITLE
Adding another CreditCard to a braintree vault using a payment_method_nonce

### ISSUE THREAD

**Issue by yosi-dediashvili** [activemerchant/active_merchant#2647]
Hi,

It seems that the `store` method of the blue gateway is only supporting the `payment_method_nonce` if the customer doesn't exist already.

i.e., if the customer already exists in Braintree, it's not possible to add a card using a nonce.

Is that really the case or am I missing something?

**Comment by bpollack** [comment]
That's a question you'd really need to ask Braintree, unfortunately; it doesn't sound as if it's a bug in Active Merchant. If you determine based on your conversation that this is happening _due to_ a bug in Active Merchant, though, please let us know.

**Comment by yosi-dediashvili** [comment]
Braintree does support passing it, it's a matter of implementation in the gem.

the `credit_card.update` method of the gateway accepts the `payment_method_nonce` param, looking at the implementation of the gateway in active_merchant, you can see that it's not possible to provide the noncehttps://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/braintree_blue.rb#L249

On the other hand, the method being used for creating both a customer & payment method `add_customer_with_credit_card` is accepting that param:
https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/braintree_blue.rb#L215

Please let me know if I made it clearer

**Comment by bpollack** [comment]
No, that makes sense. So in that case, please feel free to open a pull request if this bug is blocking you. The core team unfortunately can't keep up-to-date on all the gateways, so it's not feasible for us to go to each gateway, make changes, and then add unit and remote tests to verify that we didn't break anything.

**Comment by yosi-dediashvili** [comment]
Sure thing.

At the moment we just implemented a wrap around the ActiveMerchant gateway that takes care of the "existing customer" flow and maintains the same interface
