### ISSUE TITLE
LitleGateway Token Purchase Expiration Date

### ISSUE THREAD

**Issue by kjbkjb** [activemerchant/active_merchant#2648]
AM v1.69.0, rails/support 4.2.9, ruby 2.3, nokogiri 1.8
https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/litle.rb#L199

When a token purchase is made, the optional element token/expDate is not available or implemented in a way that can be accessed via the api. This results in token purchases that reference a DEBIT card to be rejected by the underlying issuer on a frequent basis.  This is not a scenario that can be tested using Vantiv's test cards so it was diagnosed in production.

We have monkey-patched the class to work around this issue but hope that a future version will add expDate to token purchases.

**Comment by kjbkjb** [comment]
Please disregard for now.

**Comment by kjbkjb** [comment]
Looking back on earlier implementations, I see that the expiration date used to be passed, see:
https://github.com/activemerchant/active_merchant/blob/v1.40.0/lib/active_merchant/billing/gateways/litle.rb#L240

When token/expDate is added, the additional fields must be added to fulfill the full schema requirements.

Here are the two altered methods for your consideration
```
def add_auth_purchase_params(doc, money, payment_method, options)
  doc.orderId(truncate(options[:order_id], 24))
  doc.amount(money)
  add_order_source(doc, payment_method, options)
  add_billing_address(doc, payment_method, options)
  add_shipping_address(doc, payment_method, options)
  add_payment_method(doc, payment_method, options) ##Add options to call
  add_pos(doc, payment_method)
  add_descriptor(doc, options)
  add_debt_repayment(doc, options)
end

def add_payment_method(doc, payment_method, options) #options added to args
  if payment_method.is_a?(String)
    doc.token do
      doc.litleToken(payment_method)
      if options(:token) #backward compatible implementation for expDate
        doc.expDate("#{options[:month]}#{options[:year].to_s.last(2)}")
        doc.cardValidationNum(options[:cvv])
        doc.type(options[:type])
      end
    end
  elsif payment_method.respond_to?(:track_data) && payment_method.track_data.present?
    doc.card do
      doc.track(payment_method.track_data)
    end
  else
    doc.card do
      doc.type_(CARD_TYPE[payment_method.brand])
      doc.number(payment_method.number)
      doc.expDate(exp_date(payment_method))
      doc.cardValidationNum(payment_method.verification_value)
    end
    if payment_method.is_a?(NetworkTokenizationCreditCard)
      doc.cardholderAuthentication do
        doc.authenticationValue(payment_method.payment_cryptogram)
      end
    end
  end
end
```

**Comment by kjbkjb** [comment]
my employer requires a bunch of red tape from on-high in order for us to contribute, so this issue is my next best option.

**Comment by kjbkjb** [comment]
I'm going through the red-tape right now in order to become a contributor. We benefit, we should contribute.

**Comment by kjbkjb** [comment]
(our corporate policy says "it could take several weeks for approval of requests") 😡

**Comment by bpollack** [comment]
I'm going to close this for now, but if you ever get approval, please feel free to submit a PR.
