### ISSUE TITLE
cacert.pem outdated; NAB Transact failing

### ISSUE THREAD

**Issue by guaguasi** [activemerchant/active_merchant#2657]
Using `activemerchant 1.75.0` with `ruby 2.4.2p198` and `active_support 5.1.4` on `CentOS Linux release 7.4.1708`

NAB Transact updated their gateway certificate Nov 23rd, 10:47 AM AEDT (Sydney time) causing every subsequent transaction to fail with the very detailed `The SSL connection to the remote server could not be established` error message. Turns out it was a peer verification error. OpenSSL via the CLI connected just fine.

I ended up replacing `lib/certs/cacert.pem` in the gem source with `/etc/pki/tls/cert.pem`, which appears to be the same file as `/etc/pki/tls/certs/ca-bundle.crt`, and the transactions started to flow once more.

Am I bonkers in doing this? Is this a valid issue?

**Comment by ralleman** [comment]
This is good to know because I'm seeing the same thing. What's the correct resolution for this?

**Comment by bpollack** [comment]
Merging into #2901.
