### ISSUE TITLE
Stripe: Supported card types depending on the currency/country

### ISSUE THREAD

**Issue by jeffblake** [activemerchant/active_merchant#2681]
As per https://stripe.com/docs/currencies#presentment-currencies

"JCB, Discover, and Diners Club cards can only be charged in USD."

Looking at the source, card types are not correlated to any particular currency/country. I discovered the problem when I tried to charge a Discover card in AUD.

I was hoping to be able to instantiate a Stripe gateway with a currency (or country?) and get the correct list of brands when calling `supported_cardtypes`

**Comment by bpollack** [comment]
That's a reasonable ask, but it's not one we're likely to support.

First, while the issue you're identifying is legit, it's difficult to get that list consistently across gateways; many gateways themselves don't provide this information, and it would be a losing battle to try to keep Active Merchant up-to-date ourselves.

Second, right now, a gateway isn't (necessarily) initialized on a per-country basis; it's entirely possible to vary what country you're using from transaction to transaction with a single gateway object. So it'd be difficult to do this in a way that preserved backwards compatibility.

We may at some point start looking at a 2.0, in which case this is worth a re-look, but for now, I don't think it's something we're likely to support.
