### ISSUE TITLE
PayPal express ActiveMerchant gateway not working

### ISSUE THREAD

**Issue by ralleman** [activemerchant/active_merchant#2719]
I've reported this issue on Stackoverflow [here](https://stackoverflow.com/questions/48356451/paypal-express-activemerchant-gateway-not-working). Here's the text:

According to [this](http://jldbasa.github.io/blog/2014/01/25/rails-4-paypal-express-checkout-integration/), the ActiveMerchant PayPal Express Gateway is initialized like this:

```
paypal_options = {
  login: "API_USERNAME_HERE",
  password: "API_PASSWORD_HERE",
  signature: "API_SIGNATURE_HERE"
}

::EXPRESS_GATEWAY = ActiveMerchant::Billing::PaypalExpressGateway.new(paypal_options)
```

I'm definitely supplying a signature, yet I'm getting this error:

> An API Certificate or API Signature is required to make requests to PayPal

The PayPal initializer looks like this (found here):

```
def initialize(options = {})
    requires!(options, :login, :password)

    headers = {'X-PP-AUTHORIZATION' => options.delete(:auth_signature), 'X-PAYPAL-MESSAGE-PROTOCOL' => 'SOAP11'} if options[:auth_signature]
    options = {
        :pem => pem_file,
        :signature => signature,
        :headers => headers || {}
    }.update(options)

    if options[:pem].blank? && options[:signature].blank?
        raise ArgumentError, "An API Certificate or API Signature is required to make requests to PayPal"
    end

    super(options)
end
```

I don't understand what this initializer is doing with the signature and why it's not accepting it as per the example.

Here are the options I'm passing, which I've put to STDOUT:

```
{  
   "password"   =>"***************",
   "signature"   =>"AVtrAKGQXoUNJFduUU0pn1dewq80AK9KYWenyFwYcduz8elS85B8T0Wc",
   "allow_guest_checkout"   =>true,
   "login"   =>"********************",
   "test"   =>true
}
```

Can someone help me with this please?

Note that I'm using this in JRuby, but I don't think that makes any difference in this case.

**Comment by varyonic** [comment]
Responded on SO.

**Comment by varyonic** [comment]
Resolved [on SO](https://stackoverflow.com/questions/48356451/paypal-express-activemerchant-gateway-not-working/48426817#48426817). Can be closed.

**Comment by bpollack** [comment]
Will do! Thanks for the link and context @varyonic
