### ISSUE TITLE
Is the beanstream gateway deprecated?

### ISSUE THREAD

**Issue by budu** [activemerchant/active_merchant#2724]
Hi, we are trying the Beanstream gateway but we are not able to use the `refund` method. We only get back "You are not authorized to process Return transactions though this account." and after communicating with Bambora support we only could get this response:

> Your account is not using username and password but an api passcode to process transactions.  Your code below shows username and password.  Use the same api passcode using the following example:
> 
> https://dev.na.bambora.com/docs/references/payment_APIs/v1-0-4/

Digging a little bit deeper into their documentation, their gem (https://github.com/bambora-na/beanstream-ruby), the active merchant code doesn't seem to use anything remotely close to their API. So, is that gateway made for an older unsupported version of Beanstream? Am I missing something?

Thanks

**Comment by bpollack** [comment]
Beanstream has been replaced/superceded by Bambora, and we don't have an explicit Bambora gateway; you're right. So while I'm not sure it's fair to say it's deprecated, I'm not surprised by what you're saying, either.
