### ISSUE TITLE
DigiCert Global Root G2 certificates for Wirecard Gateway

### ISSUE THREAD

**Issue by filipebarcos** [activemerchant/active_merchant#2758]
Recently got some errors around `The SSL connection to the remote server could not be established`. After reaching out to Wirecard, we were told that certificates had to be updated, since they're now signed using DigiCert Global Root G2 key, which is missing from `lib/certs/cacert.pem`.

ActiveMerchant version `1.76.0`.

**Comment by vanboom** [comment]
Same issue for Payeezy Gateway on 3/7/2018

https://support.payeezy.com/hc/en-us/articles/223607367-Payeezy-Gateway-SSL-Digital-Certificate-Update-Details
