### ISSUE TITLE
First Data E4 Now requires new certs.

### ISSUE THREAD

**Issue by betam4x** [activemerchant/active_merchant#2782]
Can you please explain to me how to get this working?  I'm no SSL expert by any means.  

See: 
https://support.payeezy.com/hc/en-us/articles/223607367-Payeezy-Gateway-SSL-Digital-Certificate-Update-Details

**Comment by bc-anna** [comment]
This is the fix - https://github.com/activemerchant/active_merchant/pull/2759 - but there's been no version bump since so you can always point to the latest master sha in the meantime.

**Comment by betam4x** [comment]
Thank you SO MUCH!

**Comment by bdewater** [comment]
@bc-anna 1.78 was [released last week](https://rubygems.org/gems/activemerchant/versions/1.78.0) which includes that fix 😄

**Comment by bc-anna** [comment]
Excellent, thanks for the update @bdewater 🙇

**Comment by bdewater** [comment]
yw!
