### ISSUE TITLE
 TLS v1.2 compatibility in BeanStream Gateway

### ISSUE THREAD

**Issue by atul25khanduri** [activemerchant/active_merchant#2812]
We're using an older version of Rails (v 3.2) and activemerchant (v 1.50.0) in an Application. Recently we got a notification from BeanStream Payment Gateway that they'll remove the support of TLS 1.0 & TLS 1.1 from 30th April.

In our server, we've executed following command to check the TLS version.

```
openssl s_client -connect api.na.bambora.com:443
```

Output:

> SSL-Session:
>     Protocol: TLSv1.2
>     Cipher: AES256-GCM-SHA384

I just want to make sure that we're also using the higher version of TLS in the application using this gem.

Kindly confirm and let me know if I'll have to update its version in order to support TLS >1.1.

**Comment by jasonwebster** [comment]
This is an open source gem, supported by a community of contributors. Is there anything preventing you from checking yourself?

**Comment by atul25khanduri** [comment]
@jasonwebster Thanks for your comment.

By checking the gem, I can see that [purchase method](https://github.com/activemerchant/active_merchant/blob/v1.50.0/lib/active_merchant/billing/gateways/beanstream.rb#L81-L90) is being used for normal payments. Then, https://www.beanstream.com/scripts/process_transaction.asp LIVE URL is [being used](https://github.com/activemerchant/active_merchant/blob/v1.50.0/lib/active_merchant/billing/gateways/beanstream/beanstream_core.rb#L73) as BeanStream API endpoint, which is called from [post method](https://github.com/activemerchant/active_merchant/blob/v1.50.0/lib/active_merchant/billing/gateways/beanstream/beanstream_core.rb#L326-L335).

But I'm still not sure which TLS version it uses.

Can you please shed some more information to help me find the TLS version we're using.

**Comment by atul25khanduri** [comment]
Also, there's no [`ssl_version`](https://github.com/activemerchant/active_merchant/blob/v1.50.0/lib/active_merchant/posts_data.rb#L8) set on [request](https://github.com/activemerchant/active_merchant/blob/v1.50.0/lib/active_merchant/posts_data.rb#L51) and on [response body](https://github.com/activemerchant/active_merchant/blob/v1.50.0/lib/active_merchant/posts_data.rb#L77), I can only see following:

> trnApproved=1
> trnId=10015006
> messageId=1
> messageText=Approved
> trnOrderNumber=10
> authCode=TEST
> errorType=N
> errorFields=
> responseType=T
> trnAmount=143.49
> trnDate=4/22/2018+6:21:59+AM
> avsProcessed=1
> avsId=N
> avsResult=0
> avsAddrMatch=0
> avsPostalMatch=0
> avsMessage=Street+address+and+Postal/ZIP+do+not+match.
> cvdId=5
> cardType=VI
> trnType=P
> paymentMethod=CC

**Comment by bpollack** [comment]
If your local Ruby speaks TLS 1.2, then so will Active Merchant. Generally speaking, we rely on the system for underlying capabilities. There's an ability to override minimum supported versions, but that's not applicable here.
