### ISSUE TITLE
MercadoPago statement_descriptor attribute is working?

### ISSUE THREAD

**Issue by MartinOGE** [activemerchant/active_merchant#2817]
I set the value for :statement_descriptor in the options hash with a 12 chars value (all caps, no special characters).
However after "purchase" is executed successfully, its response comes with the :statement_descriptor set in "MERCADOPAGO", and not with the value I set.
Is this the expected behavior?

**Comment by bpollack** [comment]
Active Merchant definitely sets it correctly (see https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/mercado_pago.rb#L179 , which seems to properly set `:statement_desciptor`), but Mercado Pago definitely always returns `WWW.MERCADOPAGO.COM` based on our unit test's sample output. So, I'm not honestly sure. What I'd ask is for you to take a look at the docs and see if we've got a bug in the implementation. If we do, I'm happy to take a look, but the library seems to be functioning correctly as-written.
