### ISSUE TITLE
ActiveMerchant::ConnectionError:The SSL connection to the remote server could not be established

### ISSUE THREAD

**Issue by neha-p6** [activemerchant/active_merchant#2826]
We are using active merchant for credit card payments. 
We have ruby 2.2.4, activemerchant locked at 1.43.3
No code is changed, the ssl certificate is also valid but active merchant suddenly has started giving 'ActiveMerchant::ConnectionError:The SSL connection to the remote server could not be established error

**Comment by tmac** [comment]
@neha-p6 I was just about to submit an issue for this as well. We were able to fix it by monkey patching the live site url:

https://gist.github.com/tmac/8483373d86a01542776a82824e8d421f

Note that updating to the latest version of ActiveMerchant should solve the issue as well. 

I believe that this is the root of the problem:

https://community.developer.authorize.net/t5/News-and-Announcements/SSL-Certificate-Updates-for-Legacy-SDKs/m-p/62935#M207

Thanks for the warning Authorize.net! 

If AM wants to continue supporting those legacy endpoints those older versions are going to have to be patched with the updated certs.

**Comment by seebq** [comment]
We have activemerchant locked at 1.50.0 and had to do this to get our older legacy app working again.  Confirmed this monkey patch worked.  I added to rails initializers with a comment linking the developer announcement.

Longer term we should update the certs, not just that one URL.

Thanks for posting this.

👍

**Comment by bpollack** [comment]
Seems like there are a couple things going on here, but the ultimate fix is certs, so merging this into #2901.

**Comment by vanboom** [comment]
This error is now happening today on `1.126.0` with the FirstdataE4 gateway -- is anyone else experiencing this error now?
