### ISSUE TITLE
custom CA bundle

### ISSUE THREAD

**Issue by wedy** [activemerchant/active_merchant#2828]
Hi guys, I have my own cert.perm and currently the cert.perm it's hardcoded in `lib/certs`

I am thinking to add this gem https://github.com/settingslogic/settingslogic & https://github.com/bkeepers/dotenv or something similar

so everyone can freely configure their custom CA bundle in their Environment Variable if they want to, 
default value will be `lib/certs/cacert.perm`

I am happy to contribute this, I just want to know what you guys think?

**Comment by bpollack** [comment]
Merging into #2901.
