### ISSUE TITLE
line items missing in receipt?

### ISSUE THREAD

**Issue by sanjaygir** [activemerchant/active_merchant#2829]
I am unable to get answer from either stackoverflow or paypal community so i am turning here for last resort. 

The problem i am facing is i am unable to make the paypal receipts show the line items. In the order details section of the receipt the name and description of items are missing. I have passed items in setup_purchase. Do i need to pass items in EXPRESS_GATEWAY.purchase() as well. Please look at the stackoverflow link below for the image of the issue. I appreciate your help. Thanks! 

 ```

      response = EXPRESS_GATEWAY.setup_purchase(total,
      
        ip: request.remote_ip,
        return_url: confirm_url,
        cancel_return_url: cart_item_index_url,
        currency: "USD",
        allow_guest_checkout: true,
        items: itms
      
      )
      
```
      

https://stackoverflow.com/questions/50129860/line-items-missing-in-paypal-receipt

**Comment by bpollack** [comment]
This isn't a bug with Active Merchant, and this issue tracker isn't the right place to ask this question. I'm sorry that you're not getting a response on StackOverflow; perhaps reach out to PayPal?
