### ISSUE TITLE
Authorize.net has changed their server

### ISSUE THREAD

**Issue by gles8705** [activemerchant/active_merchant#2833]
I've been on the phone with Authorize for the past week.  It appears that they have changed their server endpoint from:
`secure.authorize.net`
to
`secure2.authorize.net`

https://github.com/activemerchant/active_merchant/blob/161657ae1a0beac052a14d7eba2e254cbf68ad18/lib/active_merchant/billing/gateways/authorize_net.rb#L32

**Comment by brandoncc** [comment]
Thank you! I combined this url with https://gist.github.com/tmac/8483373d86a01542776a82824e8d421f for a working patch.

**Comment by bpollack** [comment]
That URL is from 2014; we fixed this a very long time ago. I suspect you're using an out-of-date gem, but let me know if you're seeing this on 1.78.
