### ISSUE TITLE
currencies_with_three_decimal_places, currencies_without_fractions inconsistently mentioned in gateways.

### ISSUE THREAD

**Issue by sehgalmayank001** [activemerchant/active_merchant#2881]
Hi, while reading this https://github.com/activemerchant/active_merchant/wiki/Contributing#setting-the-money-format, I realized inconsistency in mentioning currencies_with_three_decimal_places and currencies_without_fractions among gateway. If a currency is in currencies_without_fractions, shouldn't it be so for all gateways? The similar scenario applies to currency in currencies_with_three_decimal_places. 

https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateway.rb#L129
look at the currencies_without_fractions
in stripe.rb MGA is also mentioned currencies_without_fractions and LKA in braintree_common.rb while ["BYR", "CVE", "ISK"] are not mentioned for latter 2 gateways.
 
Also, here the list of currencies_with_three_decimal_places is empty.

https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/worldpay.rb#L12
this list is defined for WorldPay, Is this a special case?

https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/credorax.rb#L21
here JOD is also mentioned in  currencies_with_three_decimal_places.

are these special cases?

**Comment by jychen7** [comment]
btw, @sehgalmayank001 
we can use permalink to show code snip in same repo
e.g.

https://github.com/activemerchant/active_merchant/blob/84d758583c3a55afa6478fd8c9bea33a78fef2b8/lib/active_merchant/billing/gateway.rb#L129

https://github.com/activemerchant/active_merchant/blob/84d758583c3a55afa6478fd8c9bea33a78fef2b8/lib/active_merchant/billing/gateways/worldpay.rb#L12

https://github.com/activemerchant/active_merchant/blob/84d758583c3a55afa6478fd8c9bea33a78fef2b8/lib/active_merchant/billing/gateways/credorax.rb#L21

**Comment by sehgalmayank001** [comment]
@jychen7 I need to be sure of it.
take this link https://www.currency-iso.org/dam/downloads/lists/list_one.xls
or https://en.wikipedia.org/wiki/ISO_4217
Both have the similar list, i.e. there is supposed to be standard based on  ISO 4217

**Comment by sehgalmayank001** [comment]
[https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateway.rb#L129](url)

**Comment by bpollack** [comment]
Theoretically, yes, there is one single list, and every gateway should there to it. In practice, no, different gateways have different lists of what they consider three-decimal or zero-decimal currencies, if for no other reason than the lists change regularly, and gateways take time to catch up. (We literally hit an issue with this last week where a gateway that was using the master list broke because we added a new currency as zero-decimal they didn't yet support.) So while I wish there could just be One True List, there simply can't be in practice.
