### ISSUE TITLE
Purchase parameters for RedsysGateway.

### ISSUE THREAD

**Issue by gurmindersingh4260** [activemerchant/active_merchant#2932]
I am trying to integrate payment gateway for Redsys. I am using the purchase method.  
gateway.purchase(money, payment, options = {}) 
I just want to know about parameter details what constitutes of money and payment.

**Comment by bpollack** [comment]
Take a look at [the Getting Started guide](https://github.com/activemerchant/active_merchant/wiki/Getting-Started) and the rdoc for general guidelines, and the Redsys documentation for what exact options you'll need to pass. We don't keep documentation for each gateway, since their requirements can change, but the combo of the above + Redsys' own documentation should get you going.

**Comment by varyonic** [comment]
Don't be afraid to [read the code](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/redsys.rb). In the case of Redsys payment can be an ActiveMerchant::Billing::CreditCard or a String credit_card_token representing a previously tokenized card.

**Comment by gurmindersingh4260** [comment]
I am still getting the following error.
 ' SIS0252 '  =>  ' The trade does not allow card sending '.
I am sending the parameters as per docs.
credit_card = ActiveMerchant::Billing::CreditCard.new(
  :number => number,
  :month => 10,
  :year => 2010,
  :first_name => 'Bob',
  :last_name => 'Smith',
  :verification_value => '111', #verification codes are now required
  :type => 'visa'
)
customer_credit_card = ActiveMerchant::Billing::CreditCard.new(credit_card)
response = GATEWAY.purchase( 200 , customer_credit_card,  options )   

Is there anything special needed to done for redsys?

**Comment by varyonic** [comment]
> SIS0252: Merchant does not allow card to be sent

Probably related to your account setup, try your Redsys technical support.

**Comment by gurmindersingh4260** [comment]
I have contacted Redsys. They are not supporting for credit card params as POST params. Is there any other way to redirect to Rerdsys website and make the payment over there using activ merchant?
