### ISSUE TITLE
Remove American Express as a card option

### ISSUE THREAD

**Issue by domi91c** [activemerchant/active_merchant#2982]
My client wants an error to be returned when a user tries to use an American Express card. I'm looking through the code now but was hoping someone could give me an idea of how best to go about this.

Thanks

**Comment by bpollack** [comment]
You should be doing that on your end, prior to calling into Active Merchant. It's quite easy: cards have dedicated BINs, so you would just ban the American Express ones (IIRC, card numbers that start with 34 or 37).
