### ISSUE TITLE
Stripe level3 breaks if line items present, but no merchant_reference provided

### ISSUE THREAD

**Issue by jeffblake** [activemerchant/active_merchant#3008]
Shedding some more visibility on this PR comment as it's bound to affect some other people:

This broke my company's Stripe Connect integration with all of our clients, appears to be due to the fact that we have always exposed `line_items` to the post data. The Stripe error we are getting (and we are not in the level3 beta) is:

```
{"error"=>{"code"=>"parameter_missing", "doc_url"=>"https://stripe.com/docs/error-codes/parameter-missing", "message"=>"Missing required param: level3[merchant_reference].", "param"=>"level3[merchant_reference]", "type"=>"invalid_request_error"}}
```

_Originally posted by @jeffblake in https://github.com/activemerchant/active_merchant/pull/2996/comment#issuecomment-426488383_

**Comment by bpollack** [comment]
Level 3 is in private beta, which is why you can't find docs. But I also can't repro what you're seeing. I added the following unit test to Stripe locally, and it passes:

```ruby
  def test_line_items_not_included_when_absent
    @gateway.expects(:add_creditcard)

    response = stub_comms(@gateway, :ssl_request) do
      @gateway.purchase(@amount, @credit_card, @options)
    end.check_request do |_method, endpoint, data, _headers|
      assert_not_match(%r{line_items}, data)
    end.respond_with(successful_purchase_response)

    assert_success response
    assert response.test?
  end
```

`line_items` is likewise only supposed to be included when present. Could you give me an idea how you're invoking this?

**Comment by jeffblake** [comment]
Is that test hitting the Stripe servers? I'm getting the error directly from Stripe when the `line_items` are passed into the `@options`

I'm calling the `capture` method on the gateway from an authorized payment. I don't know / haven't checked if the bug also occurs on the `purchase` method. I'm using customer profiles, 


```
  def capture(cents, response_code, gateway_options)
    provider.capture(cents, response_code, adjusted_gateway_options(gateway_options))
  end
```

where `gateway_options[:line_items]` is present.

**Comment by bpollack** [comment]
@jeffblake To be clearer, why are you passing in `line_items`? It was previously not honored by the gateway at all, so it would've been a no-op; it's now honored, but assumes you know what data to pass.

Or conversely, since the comments on this ticket bring me to understand you added `line_items` as an attempt to rectify the issue, what were you initially including that trigger _any_ level 3 fields getting added?

**Comment by jeffblake** [comment]
Sorry, let me be more clear. Our software supports multiple payment gateways. `line_items` has always been there, from an Authorize.NET integration. Authorize.NET expects different parameters than Stripe's level3... so I think there should be some validation done within this library so that errors aren't triggered.

**Comment by jeffblake** [comment]
I appreciate the response, and understand your position. I suppose I will have to refactor `GatewayOptions` and make it more gateway-specific.
