### ISSUE TITLE
Stripe Application Fee refund intended behaviour unclear

### ISSUE THREAD

**Issue by jasonwebster** [activemerchant/active_merchant#3116]
When specifying the `refund_fee_amount` on a Refund using the Stripe gateway, Active Merchant makes three different API requests:

1. Issue the actual refund against the charge
2. Fetch the original application fee from the charge
3. Issue the application fee refund against the original application fee

Currently, if either 2 or 3 fail, this treats the entire process as failed, which is not true. This process is not transactional, and the actual refund which had already been done has succeeded, and is not rolled back (which isn't possible to do anyway)

Wether or not this is intended is hard to discern. 

This entire process is wrapped in a `MultiResponse.run` call which indicates that only the first request should be used to determine the overall status.

https://github.com/activemerchant/active_merchant/blob/a427610459934a8068287d1270ad41c34c634624/lib/active_merchant/billing/gateways/stripe.rb#L153-L160

However, both fetching the  app fee and refunding the application fee override this behaviour by calling `application_fee_response!` which forces the Response object into a failed state if either of these requests failed.

https://github.com/activemerchant/active_merchant/blob/a427610459934a8068287d1270ad41c34c634624/lib/active_merchant/billing/gateways/stripe.rb#L526-L528

Since this behaviour cannot be transactional, I strongly recommend that we remove that latter workaround and let the `MultiReponse.run(:first)` behaviour do its job and only care about the status of the actual refund.

/cc @curiousepic because if I recall, you recently (well, recent in active merchant terms!) worked on this.

**Comment by curiousepic** [comment]
@jasonwebster Sorry for the wait; I agree this is not optimal. This aspect was not brought discussed in the PR, so the current behavior was likely not fully considered, rather than considered desirable. And nothing comes immediately to mind that I would prefer over the proposed change.
