### ISSUE TITLE
Support for Stripe Payment Intents API

### ISSUE THREAD

**Issue by matthewopk** [activemerchant/active_merchant#3197]
[Payment Intents API](https://stripe.com/docs/payments/payment-intents) is the new SCA(Strong Customer Authentication)-ready method recommended by Stripe.

Is there any plan to support it in ActiveMerchant?
I can volunteer to implement it as I need it for my current project. Would you like me to submit a PR?

**Comment by ericschultz** [comment]
I would be willing to assist on this. A project I'm working on will be moving to active_merchant though so I'm still new to how active_merchant works.

**Comment by ericschultz** [comment]
@matthewopk just wanted to bump this. I'm still interested in helping

**Comment by matthewopk** [comment]
@ericschultz Thanks! I'll start working on it next month (on vacation right now). I'll ping you when I release my first PR.

**Comment by gretch** [comment]
I am keen to help as well.

**Comment by matthewopk** [comment]
I found out there are a lot of Stripe API endpoints `active_merchant` doesn't cover and implementing them would be the same as rewriting the whole official Stripe gem. Also by default active_merchant uses a very old version of Stripe API, and I'm not sure how compatible it is with the newest API version out of the box. So I decided to move to the official Stripe gem instead.

For those interested, this commit implements some of the methods https://github.com/n-studio/active_merchant/commit/4f4ef325073bfbdbb6397e4ce786669dcda3335e

I'm closing the issue.

**Comment by ericschultz** [comment]
@matthewopk thanks for what you've done so far!

Are there particular API endpoints that are necessary for payment intents which are not supported by `active_merchant` other than the ones you've implemented? If so, would you have a list of them? Even partial list would be super helpful to give others a pointer on how to move forward.

Thanks again, commit you provided is very helpful for others.

**Comment by ericschultz** [comment]
@matthewopk sorry to bump again.

I was wondering if you had a list of the particular API endpoints that are necessary for payment intents which are not supported by active_merchant other than the ones you've implemented? Even a partial list would be super helpful to give others a pointer on how to move forward.

**Comment by matthewopk** [comment]
@ericschultz Hi! Sorry for the late reply.
My commit doesn't cover the `SetupIntents` API and `list all payment intents`.
It should cover most of the payment intents API, although I didn't have time to test it on a real life example. I think the next step would be to ask a Stripe representative if the default Stripe api version [2015-04-07](https://github.com/activemerchant/active_merchant/blob/e860edecdc8a700925b72b9b3febed7fbfee5c85/lib/active_merchant/billing/gateways/stripe.rb#L592) is compatible with Payment Intent and Setup Intents. If not, we have to update the version and make sure existing methods won't break.
