### ISSUE TITLE
Support for Stripe SCA (PSD2)

### ISSUE THREAD

**Issue by dinophile** [activemerchant/active_merchant#3288]
In light of the new changes coming up this autumn we've been in contact with Stripe and are currently working on updates to use their new Payment Intents API.

So far progress completed:
- Have create/update/get methods
- Update method takes into account three steps for payment: confirm/capture/cancel
- Some tests covering common use cases

Still to do:
- Find all reasonable test cases and flesh out tests for them
- Confirm QA plan
- Submit PR

If anyone out there would like to get in touch to help with beta testing that would be great! 

Cheers! 😄

**Comment by trag-stripe** [comment]
Thanks @dinophile -- Are there beta releases available to point to for testing from this issue and what you're looking for in terms of testing? Perhaps a checklist like @mindlapse wrote

**Comment by dinophile** [comment]
@trag-stripe Not quite yet! Still have some cleanup to run and tests to write but hoping to have a branch up soon. I'll get in touch with @mindlapse to get a better idea of what we'd need for QA and will post back here ASAP.

**Comment by trag-stripe** [comment]
Ok sounds great - I think a post which lays out specific tasks will get folks willing to take on parts - check out this format for inspiration: https://github.com/tipsi/tipsi-stripe/issues/448#issuecomment-514229197

**Comment by mindlapse** [comment]
We've opened a Discord channel for Active Merchant for collaboration around this topic:
https://discord.gg/kbBQDk7

In terms of a checklist we'll get one set up on this thread, thank you @trag-stripe !

**Comment by dinophile** [comment]
So far our list of tasks include:

- Invoke `create_intent` method from the `authorize` method
- Invoke `create_intent` method from the `purchase` method
- Go through existing tests to see if the following have sufficient coverage:
- - Create Intent test assertions
- - Update Intent test assertions
- - Retrieve Intent test assertions
- Verify in our test dashboard that the correct behaviour is seen
- Update documentation needs 
- - Need to point to new PI API version
- - Need to inform devs that any async behaviour is their own to manage


Out of scope:
- Incorporate the SetupIntent API

**Comment by dinophile** [comment]
And thanks to @britth for the win! PR submitted already: https://github.com/activemerchant/active_merchant/pull/3290

Will close this issue and let the PR take over!
