### ISSUE TITLE
uninitialized constant ActiveMerchant::Billing::StripePaymentIntentsGateway

### ISSUE THREAD

**Issue by waaux** [activemerchant/active_merchant#3333]
I want to use the new Stripe Payment Intents gateway and I updated to the latest activemerchant 1.97.0  Trying to run my rails project I'm getting: 
uninitialized constant ActiveMerchant::Billing::StripePaymentIntentsGateway

Is the new stripe gateway Payment Intents in this 1.97.0 version??

**Comment by mrjamesriley** [comment]
It seems not, according to the Changelog, it's yet to be released:
https://github.com/activemerchant/active_merchant/blob/master/CHANGELOG

**Comment by waaux** [comment]
Thanks @mrjamesriley
