### ISSUE TITLE
Cannot establish SSL connection with Authorize.net

### ISSUE THREAD

**Issue by llhupp** [activemerchant/active_merchant#3565]
Making requests to authorize.net results in SSL errors since new certs went into effect today. The new cert can be found here:

https://support.authorize.net/s/article/How-do-I-obtain-Authorize-Nets-SSL-Certificate-for-my-host-solution-provider

For others needing an immediate fix, I hotfixed my app by adding that cert to the pem file in this repo and monkeypatching with a file like `config/initializers/active_merchant.rb`:
```
Rails.application.config.after_initialize do
  ActiveMerchant::Connection::CA_FILE = Rails.root.join('certs', 'active_merchant.pem').to_s
end
```

**Comment by llhupp** [comment]
o nevermind... this is solved by [this commit](https://github.com/activemerchant/active_merchant/commit/fc9e4e4673a1d66f64913a02b85552bfe0d04f06#diff-8d57cfb6085f89f7a79aeefea9c69f96) and I'm just too far behind. I'll see myself out.

**Comment by jonknapp** [comment]
You're not the only one that got bit by this :) Thanks for posting your solution and follow-up to make it easier for me to get back to dinner.
