### ISSUE TITLE
header field value cannot include CR/LF with Stripe

### ISSUE THREAD

**Issue by wsmoak** [activemerchant/active_merchant#3660]
We recently started seeing "header field value cannot include CR/LF" when attempting to use Stripe.

This is the problematic line: 
https://github.com/activemerchant/active_merchant/blob/8b5d2ac8abc859246c8ce3fc0b9c3d2fe5d46bb4/lib/active_merchant/billing/gateways/stripe.rb#L616

Apparently Stripe has started issuing secret keys (access tokens) that are _much_ longer, and the plain `encode64` method will insert newlines in long strings.

The fix is to switch to the `strict_encode64` method, which does not.

This article helped us find the problem: 
https://stackoverflow.com/questions/2620975/strange-n-in-base64-encoded-string-in-ruby

**Comment by nfriend21** [comment]
We just ran into this problem as well.

**Comment by fred-stripe** [comment]
A better solution here would be to use `Bearer` authentication, which [is supported by the Stripe API as well](https://stripe.com/docs/api/authentication).

> This is the problematic line:
> https://github.com/activemerchant/active_merchant/blob/8b5d2ac8abc859246c8ce3fc0b9c3d2fe5d46bb4/lib/active_merchant/billing/gateways/stripe.rb#L616

Changing this line to the following would repair the error and not require string replacement / newline stripping on the base64 output:
```ruby
'Authorization' => 'Bearer ' + key.to_s,
```

**Comment by dan003400** [comment]
We are now seeing this issue popup as well on newer Stripe accounts.

Any plans to push out a PR?

**Comment by dan003400** [comment]
> We recently started seeing "header field value cannot include CR/LF" when attempting to use Stripe.
> 
> This is the problematic line:
> https://github.com/activemerchant/active_merchant/blob/8b5d2ac8abc859246c8ce3fc0b9c3d2fe5d46bb4/lib/active_merchant/billing/gateways/stripe.rb#L616
> 
> Apparently Stripe has started issuing secret keys (access tokens) that are _much_ longer, and the plain `encode64` method will insert newlines in long strings.
> 
> The fix is to switch to the `strict_encode64` method, which does not.
> 
> This article helped us find the problem:
> https://stackoverflow.com/questions/2620975/strange-n-in-base64-encoded-string-in-ruby

Looks like this was already committed a few weeks ago:

https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/stripe.rb#L616

**Comment by dan003400** [comment]
After updating my ActiveMerchant gem the new stripe accounts are now working.
