### ISSUE TITLE
Braintree Blue Store does not follow standard arguments

### ISSUE THREAD

**Issue by danwetherald** [activemerchant/active_merchant#3666]
When using the Braintree Blue gateway, typically the store will take the payment method nonce as the first argument and the options following that.

This causes issues for platforms that are using Active Merchant as a standard implementation for multiple gates where a "gateway" should be treated in a similar manner if it is a Braintree gateway or a Auth.net gateway.

All the unit and remote tests are only done by using Active Merchant credit cards and absolutely no concept of using client side card nonces to create new customer/cards on file using the store method.

**Comment by curiousepic** [comment]
Marking this "of interest" before a cleanup of stale issues
