### ISSUE TITLE
Authorize.net CIM Gateway has inconsistent XML response for getTransactionListForCustomer

### ISSUE THREAD

**Issue by joeyparis** [activemerchant/active_merchant#3797]
I am attempting to extend the Authorize.net CIM gateway class to include the `getTransactionListForCustomer` API endpoint. The problem is the Authorize.net API returns `getTransactionListResponse` instead of the expected `getTransactionListForCustomerResponse`. I spoke with the Authorize.net developers and they are going to review this issue, but have concerns that they won't be able to change the response as too many services are already built around how it is now.

I'm opening this issue with the expectations that they won't be able to make this change to the API meaning ActiveMerchant will have to account for this inconsistency. What would be the best approach for handling this inconsistency?

**Comment by joeyparis** [comment]
My proposed solution is to modify the `parse` method like this:
```ruby
      def parse(action, xml)
        cim_action = action == :get_transaction_list_for_customer ? 'getTransactionList' : CIM_ACTIONS[action]
        xml = REXML::Document.new(xml)
        root = REXML::XPath.first(xml, "//#{cim_action}Response") ||
               REXML::XPath.first(xml, '//ErrorResponse')
        response = parse_element(root) if root

        response
      end
```
I'm not particularly fond of it, but it does get the job done.

**Comment by curiousepic** [comment]
Marking this "of interest" before a cleanup of stale issues
