### ISSUE TITLE
CyberSource: invalidField c:secCode

### ISSUE THREAD

**Issue by 1990prashant** [activemerchant/active_merchant#3836]
Hi,

I am using CyberSource Payment Gateway and trying to use check payment method, but it is raising the below error 

* "One or more fields contains invalid data", "invalidField"=>"c:secCode" *

Steps:

cs = ActiveMerchant::Billing::CyberSourceGateway.new(login: "myLogin", password: "myPassword", test: true, nexus: "WI CA QC IN")

options = {
  order_id: '1003',
  currency: 'USD',
  email: 'email@gmail.com',
  billing_address: {address1: "441", city: "New York", state: "NC", zip: "00000", country: "US"},
  shipping_address: {address1: "441", city: "New York", state: "NC", zip: "00000", country: "US"},
  owner_uuid: 'dsfajs23e23r2urr3h2rn-nbds'
}

def check(options = {})
  defaults = {
    name: 'Prashant Mishra',
    bank_name: 'Bank of Elbonia',
    routing_number: '244183602',
    account_number: '15378535',
    account_holder_type: 'personal',
    account_type: 'checking',
    number: '1',
  }.update(options)

  ActiveMerchant::Billing::Check.new(defaults)
end

res = cs.purchase(1000, check, options)

Can anyone please suggest me what am I doing wrong.

Thanks in advance.

**Comment by curiousepic** [comment]
Marking this "of interest" before a cleanup of stale issues

**Comment by 1990prashant** [comment]
This has been done with https://github.com/activemerchant/active_merchant/pull/4581
