### ISSUE TITLE
Worldpay cnpAPI (rename of Litle)

### ISSUE THREAD

**Issue by prashcr** [activemerchant/active_merchant#3873]
### Background
We're integrating [Worldpay's cnpAPI](http://support.worldpay.com/support/CNP-API/home.htm#introduction.htm%3FTocPath%3DIntroduction%7C_____0) at my company and I realized that this API  is technically a version upgrade of [LitleGateway](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/litle.rb) with all references to `litle` replaced by `cnp` and the version number bumped from `9.x` to `12.x`.

Context: Vantiv acquired Litle & Co, and then Worldpay acquired Vantiv

### Question
I'd like to upgrade and rename `LitleGateway` to `WorldpayCnpGateway`, would that be an acceptable contribution? I don't think we need to keep `LitleGateway` around as the new gateway is technically equivalent.

**Comment by curiousepic** [comment]
Marking this "of interest" before a cleanup of stale issues
