### ISSUE TITLE
How do I trigger specific response codes from Authorize.net? 

### ISSUE THREAD

**Issue by benlieb** [activemerchant/active_merchant#3945]
Authorize.net has an [extensive configuration](https://developer.authorize.net/hello_world/testing_guide.html) for generating specific response codes for credit card processing using zip codes and special cvv codes, etc in the sandbox.

I've made an integration to Authorize.net using ActiveMerchant, but it is unclear to me how to use it to generate specific responses from the server, especially since they've moved to using zip codes to trigger things.

How do I send a zip code with a charge request? Some of the cvv codes are supposed to trigger specific responses in the sandbox, but I they haven't worked for me.

Any help appreciated.

**Comment by curiousepic** [comment]
Marking this "of interest" before a cleanup of stale issues
