### ISSUE TITLE
Find pspReference information at Shopify

### ISSUE THREAD

**Issue by danielw81** [activemerchant/active_merchant#3968]
Hi all,
I am new to Github and don't know where to ask questions to projects. therefore, I place it here. Sorry, when I did something wrong by posting it as an issue.
Via active merchant the **pspReference** gets transfered from Adyen to Shopify. This information is stored somewhere at the order object in Shopify. See example order here: [Image](https://drive.google.com/file/d/1002Vzko9rQ5F_sj2foBcOxvG-Q8Nf8gq/view?usp=sharing)
I need to show that information inside an email notification that will be sent out with every new order to the staff. See example [here](https://drive.google.com/file/d/1A3BCtRjrGHuW8ODwU-LDmxRsJtNrOsUM/view?usp=sharing). Therefore, I need to have the correct liquid snippet that will show the pspreference. Neither Adyen, nor Shopify support could answer this question. Does anyone here know what is the correct liquid snippet?
Thanks in advance.

**Comment by brunocalderon** [comment]
@danielw81 Hi Daniel.
That code is not correct.
In order to access that information, you need to access the order transactions array.
The code would look like this, and you can check the transactions objects [in this link](https://shopify.dev/api/liquid/objects/transaction)
Hope my input helps!

```
{% for transaction in order.transactions %}
{{ transaction.[object] }}
{% endfor %}
```

**Comment by danielw81** [comment]
Hi @brunocalderon ,
sorry, I just saw this now. It helped a lot. I am almost there :-)

**Comment by kalenjordan** [comment]
Found something that *might* be it. In graphql - receiptJson

![CleanShot 2024-10-09 at 14 05 30](https://github.com/user-attachments/assets/98a889d9-1dc4-4528-9b27-2795ce95ccfa)


```{
  orders(first: 2) {
    nodes {
      id
      transactions(capturable: true) {
        id
        status
        test
        authorizationCode
        accountNumber
        paymentDetails {
          ... on CardPaymentDetails {
        paymentMethod
        totalUnsettled
        receiptJson
      }
    }
  }
}```
