### ISSUE TITLE
[Ebanx] `order_number` is not sent

### ISSUE THREAD

**Issue by abonifacio** [activemerchant/active_merchant#4295]
Ebanx accepts `order_number` documented as

> string [ 1 .. 40 ] characters
The order number, optional identifier set by the merchant. You can have multiple payments with the same order number.

See https://ebanx.github.io/api-reference/#operation/direct

This is useful when you're listening for Ebanx's notifications and you need to get the originating entity for a given payment https://ebanx.github.io/api-reference/#operation/query

Would be to add

```rb
post[:payment][:order_number] = options[:order_id][0..39] if options[:order_id]
```

to

https://github.com/activemerchant/active_merchant/blob/20ce8bfec708f2f31b0a34dac428f8795811a691/lib/active_merchant/billing/gateways/ebanx.rb#L181-L186

**Comment by dsmcclain** [comment]
Closed with #4304
