### ISSUE TITLE
StripePaymentIntentsGateway create_intent is missing add_payment_method_types

### ISSUE THREAD

**Issue by dan003400** [activemerchant/active_merchant#4671]
It looks like we are missing add_payment_method_types from the `create_intent` method, so the payment_method_types parameter is not being included in the request.

https://github.com/activemerchant/active_merchant/blob/5d657f71cdaab15237695a8fcf89436302c1c3c6/lib/active_merchant/billing/gateways/stripe_payment_intents.rb#L15-L52

**Comment by curiousepic** [comment]
Marking this "of interest" before a cleanup of stale issues

**Comment by alexdunae** [comment]
This was definitely "of interest" and [the related PR seemed to address the issue](https://github.com/activemerchant/active_merchant/pull/4672)  - @curiousepic what is the mechanism for re-opening this and getting it merged?

I'd be happy to take this issue over.  I believe this will start biting people who are trying to upgrade their Stripe API versions.  Per [Stripe's API upgrade docs](https://stripe.com/docs/upgrades#2023-08-16):

> When confirming a PaymentIntent, you cannot use error_on_requires_action. Use payment_method_types with error_on_requires_action if you wish to fail payment attempts when PaymentIntents transition into requires_action.

So it is now necessary to be able to pass `payment_method_types` when creating a Payment Intent.

**Comment by alexdunae** [comment]
I've added some tests and a changelog entry to a new PR in the hopes this makes things easier to merge: https://github.com/activemerchant/active_merchant/pull/5014
