### ISSUE TITLE
Stripe: Mark ISK as a zero-decimal currency

### ISSUE THREAD

**Issue by mottallify** [activemerchant/active_merchant#4754]
Stripe is deprecating fractional charges for ISK (Icelandic Krona). [Link to documentation](https://support.stripe.com/questions/deprecation-of-fractional-isk-charges-and-refunds). ISK needs to be added to the list of `currencies_without_fractions` for the Stripe gateway.

**Comment by aenand** [comment]
Hello @mottallify will you be creating a PR for this request or are you asking for someone else to?

**Comment by curiousepic** [comment]
Marking this "of interest" before a cleanup of stale issues
