### ISSUE TITLE
ISSUE with method ActiveMerchant::Billing::PaypalExpressGateway.cancel_recurring

### ISSUE THREAD

**Issue by nampt-3121** [activemerchant/active_merchant#4873]
Hello everyone, thank you for your helpful input. 
I'm currently facing an issue when attempting to cancel a recurring payment using PayPal. Previously, it worked perfectly fine, but in the past few days, when making a call to PayPal, it returns an error: 
`Profile Id is missing from the request. The profile ID is invalid.`

I've gone through debugging and noticed that the request being sent to PayPal is formatted as follows:

Endpoint: `https://api-3t.sandbox.paypal.com/2.0/`
Method: `POST`
Body:
```
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <env:Header>
    <RequesterCredentials xmlns="urn:ebay:api:PayPalAPI" xmlns:n1="urn:ebay:apis:eBLBaseComponents" env:mustUnderstand="0">
      <n1:Credentials>
        <n1:Username>Username</n1:Username>
        <n1:Password>Password</n1:Password>
        <n1:Subject/>
        <n1:Signature>Signature</n1:Signature>
      </n1:Credentials>
    </RequesterCredentials>
  </env:Header>
  <env:Body>
    <ManageRecurringPaymentsProfileStatusReq xmlns="urn:ebay:api:PayPalAPI">
      <ManageRecurringPaymentsProfileStatusRequest xmlns:n2="urn:ebay:apis:eBLBaseComponents">
        <n2:Version>124</n2:Version>
        <n2:ManageRecurringPaymentsProfileStatusRequestDetails>
          <ProfileID>I-XXXXXXX</ProfileID>
          <n2:Action>Cancel</n2:Action>
        </n2:ManageRecurringPaymentsProfileStatusRequestDetails>
      </ManageRecurringPaymentsProfileStatusRequest>
    </ManageRecurringPaymentsProfileStatusReq>
  </env:Body>
</env:Envelope>
```

Interestingly, changing `<ProfileID>I-XXXXXXX</ProfileID>` to `<n2:ProfileID>I-XXXXXXX</n2:ProfileID> `makes it work fine.

Could someone provide a more detailed explanation for this behavior? Also, regarding the recent days when this function stopped working, could it be due to a recent API update on PayPal's side? If so, how can we confirm that?

Thank you very much for your assistance.

**Comment by peterbysh** [comment]
Experiencing the exact same issue..

**Comment by curiousepic** [comment]
Marking this "of interest" before a cleanup of stale issues

**Comment by rdunlop** [comment]
I know it's 2 years ago, but A big Thank you @nampt-3121 for such a great description (And the solution).  I came across this issue today with an ancient project....and because of your issue report, I was able to solve it by monkeypatching the method:
```
# Customized in order to fix cancel request issue
# https://github.com/activemerchant/active_merchant/issues/4873
# Ref: https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/paypal/paypal_recurring_api.rb#L228
module ActiveMerchant # :nodoc:
  module Billing # :nodoc:
    # This module is included in both PaypalGateway and PaypalExpressGateway
    module PaypalRecurringApi
      def build_manage_profile_request(profile_id, action, options)
        xml = Builder::XmlMarkup.new :indent => 2
        xml.tag! 'ManageRecurringPaymentsProfileStatusReq', 'xmlns' => PAYPAL_NAMESPACE do
          xml.tag! 'ManageRecurringPaymentsProfileStatusRequest', 'xmlns:n2' => EBAY_NAMESPACE do
            xml.tag! 'n2:Version', API_VERSION
            xml.tag! 'n2:ManageRecurringPaymentsProfileStatusRequestDetails' do
              xml.tag! 'n2:ProfileID', profile_id
              xml.tag! 'n2:Action', action
              xml.tag! 'n2:Note', options[:note] unless options[:note].blank?
            end
          end
        end
        xml.target!
      end
    end
  end
end
```

In all my Paypal SOAP API research, and comparing the behavior of this endpoint with that of other endpoints which also use ProfileID, I was unable to find a reason why this endpoint would fail (and would be solved by your solution), and yet, it does, and it is. Thanks!
