### ISSUE TITLE
Releases missing from RubyGems

### ISSUE THREAD

**Issue by AMHOL** [activemerchant/active_merchant#5149]
Opening this issue as the following were closed due to inactivity:

* https://github.com/activemerchant/active_merchant/issues/4766
* https://github.com/activemerchant/active_merchant/issues/5013

It looks like the missing versions are:

* 1.107.0 (tag v1.107.0)
* 1.115.0 (tag v1.115.0)
* 1.122.0 (tag v1.122.0)
* 1.127.0 (tag v1.127.0)
* 1.128.0 (tag v1.128.0)
* 1.132.0 (tag v1.132.0)
* 1.134.0 (tag v134.0.0)
* 1.135.0 (tag v1.135.0)
* 1.136.0 (tag v1.136.0)

I'm not sure whether it makes sense to push them retrospectively, but it would be good to know whether new versions that are released will be pushed to RubyGems or not.

**Comment by emptyflask** [comment]
The latest three releases aren't on rubygems (newest is 1.133.0). Perhaps there's a bug in the release pipeline?

**Comment by emptyflask** [comment]
1.137.0 is there now, so maybe this is no longer relevant. Assuming no one wants to use an older version...
