### ISSUE TITLE
Bitcoin

### ISSUE THREAD

**Issue by Sjors** [activemerchant/active_merchant#688]
What would be involved to allow an active_merchant powered rails app to accept bitcoin payments? At minimum it should be able to create a [payment request](https://en.bitcoin.it/wiki/BIP_0021) and verify that the transaction took place.

The most lazy variant would generate a link with the shop's bitcoin address and a unique invoice number, which then opens the user's bitcoin wallet client. It then checks blockhain.info every 10 seconds or so to see if the transaction has been received. 

A less lazy variant would offer several ways to pay depending on the different clients out there and run it's own bitcoin node (perhaps using [bitcoin-ruby](https://github.com/lian/bitcoin-ruby)) to verify receiving the transaction.

Another approach would be to integrate with a service like [BitPay](https://bitpay.com/bitcoin-direct-deposit).

**Comment by rushingfitness** [comment]
Any progress on this at all? Would love to get Bitcoin processing on my site!
