### ISSUE TITLE
recurring payment with credit card

### ISSUE THREAD

**Issue by forever-sumit** [activemerchant/active_merchant#706]
i am using paypal express gateway for recurring billing with credit card.
when i pass the credit card object then i got this error message

undefined method `add_credit_card' for #ActiveMerchant::Billing::PaypalExpressGateway:0x592fa40

as i can see this method is available in 
https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/billing/gateways/paypal.rb

i don,t understand where i am worng.

my code is
credit_card = ActiveMerchant::Billing::CreditCard.new(
      :type => 'master card',
      :number => '4236201504523632',
      :verification_value => '123',
      :month => '5',
      :year => '2018',
      :first_name => 'adam',
      :last_name => 'jass')

response = PAYPAL_EXPRESS_GATEWAY.recurring(@plan.price_in_cents, credit_card,
          :description => "Payment for #{@plan.name}",
          :start_date => Date.tomorrow,
          :period => @plan.duration.capitalize,
          :frequency => 1
        )
I got error

undefined method `add_credit_card' for #<ActiveMerchant::Billing::PaypalExpressGateway:0x592fa40

activemerchant (1.32.1) lib/active_merchant/billing/gateways/paypal/paypal_recurring_api.rb:128:in `block (3 levels) in build_create_profile_request'
builder (3.0.4) lib/builder/xmlbase.rb:170:in`call'
builder (3.0.4) lib/builder/xmlbase.rb:170:in `_nested_structures'
builder (3.0.4) lib/builder/xmlbase.rb:63:in`tag!'
activemerchant (1.32.1) lib/active_merchant/billing/gateways/paypal/paypal_recurring_api.rb:125:in `block (2 levels) in build_create_profile_request'
builder (3.0.4) lib/builder/xmlbase.rb:170:in`call'
builder (3.0.4) lib/builder/xmlbase.rb:170:in `_nested_structures'
builder (3.0.4) lib/builder/xmlbase.rb:63:in`tag!'
activemerchant (1.32.1) lib/active_merchant/billing/gateways/paypal/paypal_recurring_api.rb:123:in `block in build_create_profile_request'
builder (3.0.4) lib/builder/xmlbase.rb:170:in`call'
builder (3.0.4) lib/builder/xmlbase.rb:170:in `_nested_structures'
builder (3.0.4) lib/builder/xmlbase.rb:63:in`tag!'
activemerchant (1.32.1) lib/active_merchant/billing/gateways/paypal/paypal_recurring_api.rb:122:in `build_create_profile_request'
activemerchant (1.32.1) lib/active_merchant/billing/gateways/paypal/paypal_recurring_api.rb:31:in`recurring'
app/controllers/subscriptions_controller.rb:30:in `subscribe'
actionpack (3.2.11) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.2.11) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.11) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (3.2.11) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.11) lib/active_support/callbacks.rb:425:in`_run__34193292__process_action__984126806__callbacks'
activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.11) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
activesupport (3.2.11) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.11) lib/abstract_controller/callbacks.rb:17:in`process_action'
actionpack (3.2.11) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
activesupport (3.2.11) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.11) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
activesupport (3.2.11) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.11) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
actionpack (3.2.11) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.11) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
actionpack (3.2.11) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.11) lib/abstract_controller/rendering.rb:45:in`process'
actionpack (3.2.11) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.11) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
actionpack (3.2.11) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in`call'
actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:36:in`call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in`each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.11) lib/action_dispatch/routing/route_set.rb:601:in`call'
omniauth (1.1.1) lib/omniauth/strategy.rb:177:in `call!'
omniauth (1.1.1) lib/omniauth/strategy.rb:157:in`call'
omniauth (1.1.1) lib/omniauth/strategy.rb:177:in `call!'
omniauth (1.1.1) lib/omniauth/strategy.rb:157:in`call'
omniauth (1.1.1) lib/omniauth/strategy.rb:177:in `call!'
omniauth (1.1.1) lib/omniauth/strategy.rb:157:in`call'
omniauth (1.1.1) lib/omniauth/builder.rb:48:in `call'
warden (1.2.1) lib/warden/manager.rb:35:in`block in call'
warden (1.2.1) lib/warden/manager.rb:34:in `catch'
warden (1.2.1) lib/warden/manager.rb:34:in`call'
actionpack (3.2.11) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.4) lib/rack/etag.rb:23:in`call'
rack (1.4.4) lib/rack/conditionalget.rb:35:in `call'
actionpack (3.2.11) lib/action_dispatch/middleware/head.rb:14:in`call'
actionpack (3.2.11) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.11) lib/action_dispatch/middleware/flash.rb:242:in`call'
rack (1.4.4) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.4) lib/rack/session/abstract/id.rb:205:in`call'
actionpack (3.2.11) lib/action_dispatch/middleware/cookies.rb:341:in `call'
activerecord (3.2.11) lib/active_record/query_cache.rb:64:in`call'
activerecord (3.2.11) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
activesupport (3.2.11) lib/active_support/callbacks.rb:405:in `_run__717164532__call__421525662__callbacks'
activesupport (3.2.11) lib/active_support/callbacks.rb:405:in`__run_callback'
activesupport (3.2.11) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.11) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.2.11) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.11) lib/action_dispatch/middleware/reloader.rb:65:in`call'
actionpack (3.2.11) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.11) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
actionpack (3.2.11) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.11) lib/rails/rack/logger.rb:32:in`call_app'
railties (3.2.11) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.11) lib/active_support/tagged_logging.rb:22:in`tagged'
railties (3.2.11) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.11) lib/action_dispatch/middleware/request_id.rb:22:in`call'
rack (1.4.4) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.4) lib/rack/runtime.rb:17:in`call'
activesupport (3.2.11) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.4) lib/rack/lock.rb:15:in`call'
actionpack (3.2.11) lib/action_dispatch/middleware/static.rb:62:in `call'
railties (3.2.11) lib/rails/engine.rb:479:in`call'
railties (3.2.11) lib/rails/application.rb:223:in `call'
rack (1.4.4) lib/rack/content_length.rb:14:in`call'
railties (3.2.11) lib/rails/rack/log_tailer.rb:17:in `call'
rack (1.4.4) lib/rack/handler/webrick.rb:59:in`service'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/webrick/httpserver.rb:94:in`run'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

**Comment by Dieglock** [comment]
@ntalbott  Any branch you now about activemerchant that manages recurring (subscriptions) with paypal? sdk-merchant does not work with rails 4... There should be many people searching for the option. Thanks.

**Comment by ntalbott** [comment]
@Dieglock no, since ActiveMerchant explicitly does not support recurring/subscription payments (all that remain will be removed in the next major version); they're out of scope for the library. Our recommendation is to use the given API directly or find a gem specifically targeted at it.
