### ISSUE TITLE
Payflow Common API only supports one address line

### ISSUE THREAD

**Issue by silverstreaked** [activemerchant/active_merchant#881]
### Problem

The Payflow Common API only looks at one line of addresses (address1), and seems to ignore a second address line if it is passed. PayflowExpress UK was patched to support a second line (see https://github.com/Shopify/active_merchant/commit/b19b36d2c6abe16a1c18422d3511d559d2bf0cb3), but the regular non-Express version was not. So an address like this will end up missing critical information on the PayPal end:

> [Name withheld]
> Pi Cottage <-- address1
> 37 Hamhaugh Island <-- address2
> Shepperton <-- city
> Middlesex <-- region/province
> TW17 9LP
> United Kingdom

@melari @odorcicd

**Comment by WilsonChiang** [comment]
Going to re-open this as it is still a problem that we are looking to address soon.

**Comment by bpollack** [comment]
@WilsonChiang I'm going to close this again, as it's been over a year. If you do in fact have a PR for this, though, I'm really happy to take a look.
