### ISSUE TITLE
Paypal BN Code

### ISSUE THREAD

**Issue by JoshuaNovak919** [activemerchant/active_merchant#888]
I am trying to figure out how to use the Paypal BN Code with this gem, does anyone know where i am supposed to put it?

**Comment by chiedojohn** [comment]
Hey @JoshuaNovak919 did you figure out how to do this? I'm looking to do the same thing.

**Comment by girasquid** [comment]
I poked through some of our code and it looks like this might work if you set `application_id`, like so:
```ruby

ActiveMerchant::Billing::PaypalGateway.application_id = "your BN here"
ActiveMerchant::Billing::PaypalExpressGateway.application_id = "your BN here also"
```

That's the best I've got though - if that doesn't work for you, you are on your own.

**Comment by chiedojohn** [comment]
Thanks @girasquid I'll give that a shot!
