### ISSUE TITLE
SagePay direct integration live account documentation

### ISSUE THREAD

**Issue by alagunambi** [activemerchant/active_merchant#962]
The following is my initializer file for simulator account, which works perfectly fine, 

``` ruby
gateway = ActiveMerchant::Billing::SagePayGateway.new(
        :login  => LOGIN_ID,
        :password => TRANSACTION_KEY,
      )
ActiveMerchant::Billing::Base.mode = :test
ActiveMerchant::Billing::SagePayGateway.simulate = true
```

when I switch to live account, I have vendor_name, which according to documentation is the necessary parameter for payment, I tried, the following code,

``` ruby
gateway = ActiveMerchant::Billing::SagePayGateway.new(
        :login  => LOGIN_ID,
        :password => TRANSACTION_KEY,
        :vendor_name => VENDOR,
      )
ActiveMerchant::Billing::Base.mode = :live
ActiveMerchant::Billing::SagePayGateway.simulate = false
```

and it didnt work Im always getting 

```
4000: The VendorName is invalid or the account is not active.
```

im clue less on how to setup live account, any pointers or documentation would be of great help.

More info: Rails 4.0.0, activemerchant 1.34.0

**Comment by uzaif313** [comment]
@ntalbott I am facing issues while making transaction. 
![image](https://user-images.githubusercontent.com/16485731/68176156-b7388000-ffa9-11e9-81dc-5b0578bc03e6.png)
